### ISSUE TITLE
Feature Request: Auto Connect

### ISSUE THREAD

**Issue by espiox** [neil-morrison44/pocket-sync#100]
Would it be possible to have an option to set a drive letter that Pocket Sync automatically looks at when starting the app, rather than having to manually point it there each time?

**Comment by neil-morrison44** [comment]
This'd be interesting yeah, I think it'd end up something like:
- New `Reconnect on opening app` option in settings
- When it's on it'll remember the last directory opened as a Pocket
- On opening the app it'll check if that directory exists & looks like a Pocket and auto-connect if it does
- Will need some sort of disconnect button in the UI to return to the "Connect To Pocket" screen for folks running multiple Pockets or using local folders etc

**Comment by neil-morrison44** [comment]
That's this in now, thanks for the suggestion - think it's a really noticeable improvement having it on
