### ISSUE TITLE
Instant crash/unable to open

### ISSUE THREAD

**Issue by lucas2365** [neil-morrison44/pocket-sync#104]
**Describe the bug**
The program instantly crashes or is unable to open. A window flashes with the title "PocketSync" for a frame or two then closes.

**To Reproduce**
Steps to reproduce the behaviour
1. Install PocketSync
2. Try to open program.

**Expected behaviour**
The program to open and run.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2
 - Build 22621.1702

**Comment by neil-morrison44** [comment]
The new .exe based installer might sort this out, not sure (seems to work for others on Windows 11)

**Comment by thesaltineking** [comment]
Sorry to necro, I'm having the exact same issue unfortunately.  Happens whether or not I use the .exe installer.
Windows 10 Home
22H2
19045.3570

**Comment by neil-morrison44** [comment]
I think the underlying issue causing this has been fixed now (especially if it started happening after v3.1.0)
