### ISSUE TITLE
Taito SJ Roms

### ISSUE THREAD

**Issue by gregmariotti** [neil-morrison44/pocket-sync#116]
none of the roms are still showing....I haven't had issues before......

<img width="1010" alt="Screenshot 2023-07-07 at 6 26 11 AM" src="https://github.com/neil-morrison44/pocket-sync/assets/115591167/3598a452-7d46-4ec0-8eab-1c0adeb05225">

**Comment by neil-morrison44** [comment]
The files aren’t in whichever archive you’re using - I’m not the one who puts the files up (I’d recommend asking on the FPGAming discord)
