### ISSUE TITLE
Build Pipeline: Universal macOS build or dedicated arm64 build

### ISSUE THREAD

**Issue by codeandcreate** [neil-morrison44/pocket-sync#12]
Please provide a native arm64 build for Apple Silicon macs :)

**Comment by neil-morrison44** [comment]
Need to wait for this https://github.com/actions/runner-images/issues/2187 for that

Will get it in as soon as that's available

**Comment by neil-morrison44** [comment]
Added in v2.2.0 - turns out we didn't have to wait for a universal build!

(the windows arm build has issues though)
