### ISSUE TITLE
New firmware - click - error

### ISSUE THREAD

**Issue by remy** [neil-morrison44/pocket-sync#121]
**Describe the bug**

I had a notice saying there's new firmware available (1.1 - I'm currently on 1.1-beta.7) - I click on the Fireware sidebar tab and get the following error:

```
Firmware: null
n.split("/").at is not a function. (In 'n.split("/").at(-1)', 'n.split("/").at' is undefined)
tauri://localhost/assets/index-f4e2ef5b.js:3773:1140394
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

Now clicking any tab results in the same error (but changing the `Firmware` to the specific tab).

**To Reproduce**

As above

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.6 (Big Sur)

**Comment by neil-morrison44** [comment]
`.at` is usually a quick fix so I’ll take a look at replacing it with something else next time I’m in the code - but (due to the way Apple doesn’t update the system WebKit version that gets used by what I write the app in) I can only really guarantee support for the latest 2 major versions of MacOS

**Comment by remy** [comment]
Yeah, WebKit sucks.

I suspect if you drop in the polyfill.io service it might let you leapfrog
Apple's shortcomings.
