### ISSUE TITLE
Fetch doesn't create missing folders

### ISSUE THREAD

**Issue by espiox** [neil-morrison44/pocket-sync#122]
**Describe the bug**
The new Fetch feature won't create a folder if it's missing from the Pocket

**To Reproduce**
1. Pointed to a local folder (for example C:\Output\, which contains 3 subfolders, Shadows, No Shadows, and Hardware)
2. Set destination as Pocket\Assets\gameandwatch\common\ (which already contains 2 subfolders, Shadows and No Shadows)
3. Pocket Sync sees that there are 32/33 files on the Pocket, but clicking Fetch refreshes and still displays 32/33 files (the 1 file is in Hardware).
4. Manually create the "Hardware" folder at the destination.
5. Fetch now works and fetches all 33 files.

**Desktop (please complete the following information):**
Windows 11, 22621.1928

**Comment by neil-morrison44** [comment]
Might have just forgot to test having subfolders in the local files copy

I’ll have a look & see what’s up
