### ISSUE TITLE
Core images fail to load with cache dir error

### ISSUE THREAD

**Issue by danmacpherson** [neil-morrison44/pocket-sync#125]
**Describe the bug**
Images do not load for cores. Flatpak reports the following error for each attempt to load an image:

`thread 'tokio-runtime-worker' panicked at 'failed to create cache dir: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/file_cache.rs:61:14`

Clicking on an installed core no longer takes me to the core info page too.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load Pocket Sync
2. Connect to Pocket
3. Navigate to Cores
4. Watch the progress spinner for each core

**Expected behaviour**
Core images load correctly

**Screenshots**

![image](https://github.com/neil-morrison44/pocket-sync/assets/1260665/bb95bbd8-fc6f-4ad6-930d-82733e680f1c)

![image](https://github.com/neil-morrison44/pocket-sync/assets/1260665/fffc5747-df04-4dd5-a60a-71a2b22c1288)

**Desktop (please complete the following information):**
 - OS: Linux 
 - Version: Fedora 38
 - Flatpak: 1.15.4

**Additional context**
Pocket Sync used to load core images without issue.

**Comment by neil-morrison44** [comment]
Oh, that’s annoying - if it’s easy can you try out the non-flatpak version & let me know if that works?

Unsure if it’s a Linux issue or a Flatpak issue

**Comment by danmacpherson** [comment]
Hi, Neil! Sure thing.

I installed Ubuntu 23.04 in a virtual machine and did a USB host passthrough of my pocket. Installed the pocket-sync deb onto the virtual machine and connected to my pocket. Pocket loads up fine in pocket-sync but I got the same result:

![image](https://github.com/neil-morrison44/pocket-sync/assets/1260665/4dd45901-72bc-4c8f-824a-330dbe1ec90d)

Same error message:

![image](https://github.com/neil-morrison44/pocket-sync/assets/1260665/6c0b6f3a-fbca-4093-b112-8b553387f10c)

**Comment by neil-morrison44** [comment]
Awesome, thanks,
Should be easy enough to handle it better in Pocket Sync & I’ll try and see if it’s a known issue upstream.

(I’m calling something which _should_ give me a cache directory or tell me there isn’t one on that platform & I guess it’s making up an invalid cache directory on Linux or something)

**Comment by danmacpherson** [comment]
Works great! Thanks, Neil!
