### ISSUE TITLE
MiSTer FPGA Save Sync Location Mapping

### ISSUE THREAD

**Issue by andrewkendall** [neil-morrison44/pocket-sync#132]
This may be something I have just overlooked. Is there a way to manually specify the MiSTer FPGA sync location mapping?

Currently, my Pocket GBC save sync folder maps to GAMEBOY instead of GBC on the MiSTer.

A similar situation exists with the WonderSwan/WonderSwan Color.

I am aware that MiSTer Update All recently introduced GameboyColor.mgl and WonderSwan Color.mgl, so this could be the reason for the change in location.

**Comment by andrewkendall** [comment]
I think I may have answered my own question. I took a look at the source code, and I believe the code should now be:

```typescript
fn pocket_platform_to_mister_system(platform: &str) -> Option<String> {
    Some(match platform {
        "gb" => "GAMEBOY",
        "gbc" => "GBC",
        "gg" | "sms" => "SMS",
        "pce" | "pcecd" => "TGFX16",
        "gba" => "GBA",
        "sg1000" => "SG1000",
        "arduboy" => "Arduboy",
        "genesis" => "Genesis",
        "ng" => "NEOGEO",
        "nes" => "NES",
        "snes" => "SNES",
        "supervision" => "SuperVision",
        "poke_mini" => "PokemonMini",
        "wonderswan" => "WonderSwan",
        "gamate" => "Gamate",
        _ => return None,
    })
    .map(String::from)
}
```

That should fix the GB/GBC issue. WonderSwan is more complicated because the Pocket core only seems to use wonderswan, although I believe it could be fixed by using subfolders on the Pocket.

This assumes that everyone else also has a separate GBC save folder on their MiSTer after the addition of the GameboyColor.mgl from Update All.

**Comment by neil-morrison44** [comment]
I'll have a look into this & see what makes sense now soon - did the MiSTer move existing GBC saves into the new GBC folder?

Might need to present the option to override the search directory to the user on a per-game basis or something.

**Comment by MarquisDeKazuma** [comment]
The Mister has recently had a change in the Sega Genesis, with the Genesis core being archived for a new core under MegaDrive that is more cycle accurate. They didn't have it write over the current core though which means that the new core does not point to Genesis but rather MegaDrive for save syncs. Is it possible to either give an option or change this location?

**Comment by andrewkendall** [comment]
I just checked back into this several months after opening the issue. What a phenomenal solution. Neil, an amazing job. That is all, credit where credit is due.
