### ISSUE TITLE
Crashes after selecting "Updatable

### ISSUE THREAD

**Issue by neogeo81** [neil-morrison44/pocket-sync#137]
Crashes after selecting "Updatable
![Bildschirmfoto 2023-09-04 um 15 43 55](https://github.com/neil-morrison44/pocket-sync/assets/32906058/c9690231-b2c4-4126-ab84-727ee30156a8)
".
After restart i have to confirm that the app is allowed to access the HDD again every time.

Cores: null
Attempt to read platform_id spacerace
@tauri://localhost/assets/index-6f6f5f56.js:5412:13286

**Comment by neil-morrison44** [comment]
Very strange - from the error it looks like you’re missing this file https://github.com/ericlewis/openfpga-spacerace/blob/main/dist/Platforms/spacerace.json

if you download it then put it in as Platforms/spacerace.json everything should start working again.

Can you remember how you installed the spacerace core? It shouldn’t have been possible to install it with some of the files missing…

**Comment by neogeo81** [comment]
Thanks. It worked. 
I didn't do anything fancy, installed it with the app itself.

**Comment by neil-morrison44** [comment]
That’s great, wonder what happened during the install…
