### ISSUE TITLE
List all cores with missing files.

### ISSUE THREAD

**Issue by Arithmeticae** [neil-morrison44/pocket-sync#139]
It would be incredibly swell if we had the option to view all cores that are missing files. It would be even more swell if it could be viewed as a list with the installed/required/available count easily seen.

**Comment by neil-morrison44** [comment]
I agree, however the number of files that have to be checked for the required files bit quickly adds up to the hundreds (potentially 1000+ if the CPS2 core is installed & `_alternatives` aren't being ignored).

Each "required file" gets a hash taken of it which gets checked against the latest version available to see if it can be updated, which is a fairly intense process.

So it'd mean a ~3 minute plus wait over an SD card, and potentially _a lot_ longer when connected over USB with all cores installed.

So, annoyingly, there's just no quick way of doing it - it's also why even when you do go into the info view of a core the count of required files sometimes takes a while to finish loading and that's just when it's looking at file files of one core.

I could, potentially, do it as a background task when the app detects that it's idle but that would probably be of limited use - and the user might well be doing some other file moving process which would get slowed down.
