### ISSUE TITLE
MacOS High Sierra 10.13.6: Black screen when start up pocket sync

### ISSUE THREAD

**Issue by Mika73** [neil-morrison44/pocket-sync#15]

**Comment by Mika73** [comment]
I did try pocket sync with Mac. First white window, then something flash at window quick and then black screen. I couldn’t get it working. 
![85B98966-1959-4368-9572-CE251E3D6DAE](https://user-images.githubusercontent.com/12106091/204343751-3f6785e1-5969-43e8-b6ae-e9df11a7eee3.jpeg)

**Comment by Mika73** [comment]
MacOS High Sierra 10.13.6

**Comment by neil-morrison44** [comment]
Hmm, I'm not sure what would be the thing that breaks it but High Sierra is over 5 years old ( & the app reuses the OS level browser etc ) so it definitely won't work 100%

I'm planning on putting in more error boundaries at some point soon so, in theory, if some of the app breaks it won't crash the entire app

**Comment by Mika73** [comment]
I think it does flash that start up screen of pocket sync and then black screen. It just happens so fast.

Lähetetty iPhonesta

**Comment by Mika73** [comment]
Same problem with latest update. Just try it today. White screen, flash pocket sync start up screen and black screen. 

Lähetetty iPhonesta

**Comment by neil-morrison44** [comment]
Hmmm, the bit that I thought might be what causes that is wrapped in an error boundary now so it must be something else.

10.13 should be the oldest version of MacOS supported by the thing I’m using:  https://tauri.app/v1/guides/building/macos/#setting-a-minimum-system-version but there’s probably other things I’m doing which aren’t supported.

I don’t think I’ll be able to fix this, sorry

**Comment by Mika73** [comment]
I have MacOS 10.13.6

High Sierra 

Lähetetty iPhonesta
