### ISSUE TITLE
outrueha.rom missing from openFPGA-Files archive repo

### ISSUE THREAD

**Issue by mfncl9991** [neil-morrison44/pocket-sync#16]
First of all, a big thanks in making your tool work nicely with JT cores.
The jotego core jtoutrun.zip requires outrueha.rom but the archive repo the tool uses doesn't have it.

**Comment by neil-morrison44** [comment]
There’s some missing ones - you can leave a comment on the archive.org link requesting things (I’m not the one who maintains it)
