### ISSUE TITLE
New Analogue Pocket Image is flickering

### ISSUE THREAD

**Issue by pinballgithub** [neil-morrison44/pocket-sync#160]
Thanks for you brilliant and very easy to use tool. You changed the rotating Analogue Pocket image . Unfortunatly it is flickering now and the picture is distorted by grey boxes.

**Comment by neil-morrison44** [comment]
Can you take a screenshot? What OS / version are you using?

**Comment by pinballgithub** [comment]
![1](https://github.com/neil-morrison44/pocket-sync/assets/99117933/0a4ab51a-3e57-4e12-9f01-9e49c2955cc0)
![2](https://github.com/neil-morrison44/pocket-sync/assets/99117933/da6d1eb8-e71f-460d-8a17-e8216def65cf)

I am using Windows 10  - I am using your latest revision of Pocket Sync (online updated). It seems related to the different colouring. Black picture are OK, other anlalogue pocket color are flickering and have the black square inside.

**Comment by neil-morrison44** [comment]
Thanks for the screenshots.
That’s strange, I’ll try and replicate it.

What graphics card do you have?

**Comment by pinballgithub** [comment]
Dear Neil, it is a Dell PC with 2 graphic cards: Intel HD 4600 and NVDIA GeForce GT 750M (latest drivers). The artefacts come with both cards. In the old version of pocket sync everything was OK. Wenn the pocket turn, the black picture is OK (... or you do not see the black square artefacts). Only the transparent models show this effect. The effects are not on the frontside or backside only on the 2 left and right edges of the rotating pocket. 
![3](https://github.com/neil-morrison44/pocket-sync/assets/99117933/298755ca-20dd-4a04-9dc0-818787f2d7b7)

**Comment by JayroJones** [comment]
I have this issue as well. Windows 10, GTX 1060, latest drivers.

**Comment by neil-morrison44** [comment]
This should be fixed now in 4.1, it was something up with having the transparent part being `DoubleSide`, so it no longer is.
