### ISSUE TITLE
App opening to grey screen on macOS Ventura/Sonoma

### ISSUE THREAD

**Issue by chanunnaki** [neil-morrison44/pocket-sync#161]
**Describe the bug**
App opens no nothing but a grey screen on M1 Mac Mini

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '/Applications'
2. Double-Click on 'Pocket-Sync'

**Expected behaviour**
The app should display a UI, but there is nothing but a grey screen

**Screenshots**
![Screenshot 2023-10-15 at 13 04 03](https://github.com/neil-morrison44/pocket-sync/assets/49243628/165cacec-68f0-486a-9ebb-8ed5b3766d21)

**Desktop (please complete the following information):**
 - OS: macOS Ventura & Sonoma
 - Version 13.6 & 14.0

**Additional context**
At first it worked as normal, but after a few minutes the app froze so I force-quit. Now every time I open the app, I see nothing but a grey screen. A restart didn't help. I updated my Mac to Sonoma hoping it would fix the issue, but it didn't. I had to revert back to version 2.1.0 (final x64 .dmg) of the app for it to work on my M1 Mac mini

**Comment by chanunnaki** [comment]
I saw this closed issue with same problem, but I don't know if the underlying problem is related.

https://github.com/neil-morrison44/pocket-sync/issues/76#issue-1574350264

**Comment by neil-morrison44** [comment]
Unlikely to be the same - you’re on the same version of MacOS as I develop the app using so it should work 100%.

Which version did this start happening with? Is it just the most recent version?

**Comment by chanunnaki** [comment]
It just started happening with this latest version.

I have installed many versions now and the last one that opens without any issue is 3.0.1

Screens of 3.0.1:
![Screenshot 2023-10-15 at 13 18 42](https://github.com/neil-morrison44/pocket-sync/assets/49243628/7c886bfc-0f67-4fa5-98c4-dad074a7b673)

![Screenshot 2023-10-15 at 13 19 12](https://github.com/neil-morrison44/pocket-sync/assets/49243628/45acf7d3-61ea-4bed-a65b-c9e80c0a176b)

**Comment by chanunnaki** [comment]
Deleting both today.neil.pocket-sync cachefile and today.neil.pocket-sync preferences files and reinstalling didn't resolve the issue.

**Comment by neil-morrison44** [comment]
Ah right yeah - thanks for that, I've got a guess as to what's going wrong then.

3.1 was the version that added the "auto-reconnect" option, which is being read on start up.

If you go to `/Users/[username]/Library/Application Support/today.neil.pocket-sync/` you should have a `reconnect_when_opened.json` file - if you can let me know what its current value is to see if it's been messed up somehow & then (if I'm right) then deleting it _should_ get the app opening again

**Comment by chanunnaki** [comment]
yes!!! That worked! It was enabled and searching for an SD card that no longer exists. Thanks a million! This app is amazing!

**Comment by bstaruk** [comment]
Following the instructions here fixed the issue for me, as well.

IMO this issue should not have been closed because while there is a very hacky workaround, it's still a problem that shouldn't occur and needs to be fixed. I almost ditched this app for a competitor because I spent over an hour trying to fix this problem.
