### ISSUE TITLE
Auto-reconnect option can cause issues

### ISSUE THREAD

**Issue by neil-morrison44** [neil-morrison44/pocket-sync#162]
As found in https://github.com/neil-morrison44/pocket-sync/issues/161

Should handle invalid JSON in the atom effect that keeps the data in sync with the file & also double check the code that only reconnects when the folder is found.

**Comment by neil-morrison44** [comment]
If anyone else runs into this a copy of the JSON that’s causing it to go wrong would be really helpful

**Comment by traveling-walker** [comment]
Just experienced this with release 3.9.0 on an M2 Mini running macOS 14.1. Removing the reconnect_when_opened.json (attached) as outlined [here](https://github.com/neil-morrison44/pocket-sync/issues/161#issuecomment-1763379127) resolved this. 

[reconnect_when_opened.json](https://github.com/neil-morrison44/pocket-sync/files/12924366/reconnect_when_opened.json)

**Comment by traveling-walker** [comment]
> Just experienced this with release 3.9.0 on an M2 Mini running macOS 14.1. Removing the reconnect_when_opened.json (attached) as outlined [here](https://github.com/neil-morrison44/pocket-sync/issues/161#issuecomment-1763379127) resolved this.
> 
> [reconnect_when_opened.json](https://github.com/neil-morrison44/pocket-sync/files/12924366/reconnect_when_opened.json)

Looking at the json, it seems an extra closing curly brace is present. Manually removing that and replacing the file allows the app to open & auto-load without issue.
 
`{"enable":true,"path":"/Volumes/Pocket"}}`

**Comment by neil-morrison44** [comment]
@traveling-walker awesome, thanks for that - should just be a case of handling invalid JSON.

Will need to look into how the extra `}` is finding its way in in the first place too

**Comment by neil-morrison44** [comment]
https://github.com/tauri-apps/tauri/issues/7973

Well that explains why it's happening
