### ISSUE TITLE
Backup GB Studio Saves

### ISSUE THREAD

**Issue by joelekstrom** [neil-morrison44/pocket-sync#166]
Hey! Thanks for making this software, it's great!

Feature request: It would be great if `GB Studio/Saves` were included in the save backups, as I almost always play GB/GBC games through GB Studio to get the filters (and I imagine many others do too). Would be helpful for homebrew games too, ofc!

I tried to work around it by (ab)using the Fetch-functionality - fetching from my Pocket to my backup folder, but it didn't work since it seems the Fetch location can only be on the pocket drive 😬

**Comment by neil-morrison44** [comment]
Closing this off as part of issue clean up, I think the number of people still playing games via the GB Studio files is probably low. Likely even people exporting from GB Studio are doing it via .gb / .gbc files now.
