### ISSUE TITLE
"Required Files" Icon not representing actual file availability - jtbeta.zip

### ISSUE THREAD

**Issue by Arithmeticae** [neil-morrison44/pocket-sync#175]
Using MacOS 13.6.1 when selecting a core in Pocket Sync, the "Required Files" icon will indicate that the jtbeta.zip file is missing for all that require it, but when the dialog is open, correctly show that jtbeta.zip is in the root directory. I think the icon should not note those files as missing when determining what number of the total files are present/missing.

Going beyond that bug, I think globally that button and the X/Y displayed in it should also reflect if there are updatable files by marking them as missing. I'd like to know if there is anything _more_ to download for a specific core without having to click the button.

**Comment by neil-morrison44** [comment]
- Having the jtbeta.zip file at the root isn't enough for the cores, it gets moved to within the core's files when "Download All" is clicked (which is confusing but the way jtbeta works will probably change a little in 1.2 so I've not put too much time in it)
- I believe that the button _does_ currently count updatable files as "missing" https://github.com/neil-morrison44/pocket-sync/blob/main/src/components/cores/info/requiredFiles/index.tsx#L22 files which have been updated on an archive but not locally will come up as "wrong"

Going to close this off - feel free to reopen if I've misunderstood or it's not doing what it should be doing
