### ISSUE TITLE
Error when reading agg23's Arduboy files

### ISSUE THREAD

**Issue by Panikk11503** [neil-morrison44/pocket-sync#180]
Windows 11 22H2 22621.2506
Pocket Sync v3.10.1 x64

When going to the Cores or Games sections it has an issue with the very first core, which is agg23.Arduboy . 

Cores: null
Attempt to read platform_id arduboy
Error: Attempt to read platform_id arduboy
    at https://tauri.localhost/assets/index-27990549.js:5657:13417
    
    
![arduboy](https://github.com/neil-morrison44/pocket-sync/assets/22116474/65d3af34-e7f3-4809-94ef-292bb0ae50f2)

I'm not sure if it's a permissions issue or an issue with that specific core.  Running different compatibility modes and As Admin didn't change the error.

**Comment by neil-morrison44** [comment]
Looks similar to https://github.com/neil-morrison44/pocket-sync/issues/137 except this file instead https://github.com/agg23/openfpga-arduboy/blob/master/dist/Platforms/arduboy.json, really not sure how these cores are getting installed without all their files present (the Pocket itself will also have issues with that one missing)

**Comment by Panikk11503** [comment]
I did use pocket_updater.exe by Matt Pannella ver 2.36.2.0 as well as
Pocket Updater by RetroDriven 1.5.7 .  Not sure which one caused that to
half-install but I know I only used the RetroDriven updater once or twice
before fully switching over to Matt's updater.

**Comment by neil-morrison44** [comment]
Did putting that file into place resolve this for you?

The rarity of this is confusing since the other issue is the only other time I've heard of it & I don't think Matt's heard of it either (Retrodriven's GUI runs an, at this point fairly old, version of Matt's updater script).

I could try adding an "redownload" button on the error screen when it's a JSON error / missing file error, but that's about the extent of it - since certain files _should_ be there.

**Comment by Panikk11503** [comment]
Yeah putting that json into it did relieve the initial error, but then it moved onto Eric Lewis' Dominos core.  After I downloaded the latest release of that in full and put it on my SD card and relaunched Pocket Sync, no more errors.  I'm not sure if there is a way to avoid this problem on your end, but at the very least you can confidently point people to this same solution if their platforms folder is missing .json files in the future.  Thanks
________________________________

**Comment by Panikk11503** [comment]
Alright after a couple relaunches it came back, but still it seems to just be an issue with missing .json files.  I'll fix it manually but yeah this should be the end of this problem after I manually go get everything or delete and start over (convenience, right? lol)
________________________________

**Comment by neil-morrison44** [comment]
Should be, yeah - very strange...

That's the most missing json files I've heard of - could be worth raising an issue on Matt's / Retrodriven's updater (depending on when the cores with the issues were installed) and copying your `pocket-updater.json` (or whatever it's called) into the issue incase it's something up with that config.

I'll close off this issue
