### ISSUE TITLE
jtcps2 required files not loading when disable alternate files is unchecked

### ISSUE THREAD

**Issue by DJBabyBuster** [neil-morrison44/pocket-sync#181]
Running on latest Pocket Sync for Mac, V3.10.1

When "Skip Alternate Assets" is unchecked in settings the jtcps2 core does not load "required files."  This has been the case on the last three versions of Pocket Sync since I noticed.  Next to required files you only get "Please wait, checking files..." indefinitely (see screenshot).  I've left this screen open for hours and it never loads the files.  If I check Skip Alternate Assets in settings, jtcps2 will load the current 40 files (see screenshot), then when unchecking Skip Alternate Assets on this screen I get a spinning loading that never goes away (see screenshot) until clicking another section within Pocket Sync.  I also tried turning on Enable Fast Doanloads in the latest update, and that did not resolve the issue. 

<img width="1438" alt="Screenshot 2023-11-09 at 2 25 40 PM" src="https://github.com/neil-morrison44/pocket-sync/assets/8422984/5c65b45e-3b05-44da-9ecf-454f7237c5b2">
<img width="1437" alt="Screenshot 2023-11-09 at 2 25 32 PM" src="https://github.com/neil-morrison44/pocket-sync/assets/8422984/e96acf1d-3bb6-4127-8f37-606874076aa5">
<img width="1438" alt="Screenshot 2023-11-09 at 2 23 39 PM" src="https://github.com/neil-morrison44/pocket-sync/assets/8422984/bc23d679-0818-426e-ad7d-5056386e8799">

**Comment by neil-morrison44** [comment]
Do you have the alternative files installed? Are you ejecting the SD card or using the Pocket’s USB?

If the files are there and you’re using USB then hours probably isn’t outside of the realm of how long it’d take (it’s creating a hash of each of the ~40MB files to compare it against what it can download).
If not then something’s probably up.

I’ve been thinking about potentially switching to use the file’s modified time which would speed this up considerably but there’s a couple of pieces that need to be in place before that’s viable

**Comment by DJBabyBuster** [comment]
Accessing my sd card directly, using a sandisc extreme 512gb, I never connect the pocket via usb b/c I am aware how slow access is. 

I have alternate files for every other core installed, including Jotego betas, but it's just jtcps2 that won't load alternate files.

**Comment by Arithmeticae** [comment]
I also encounter this issue on MacOS 13.6.1 with almost the exact same behavior. I am reading the SD card directly, not through a usb connection to the Pocket. 

The CPS2 core has always been a bit of an outlier for me. Often it would never finish "checking files", but as the original reporter noted, it appears that now the blank screen always appears about a second after navigating to that core in Pocket Sync.

I did use the feature in pocket sync to cleanup the folders and while that helped a lot with other cores, it made no difference to the behavior of this one.

**Comment by neil-morrison44** [comment]
How many JSON files do you have in the core’s assets folder? If you installed the first beta of CPS2 then a later beta you could have a lot of duplicate instance json files.

I’ll have a go at replicating this next week (it works fine for me locally currently…) and see if I can get a fix in, or just speed it up as much as I can to try and get out of it by processing more files at once.

- - -
@Arithmeticae 
That issue being Mac only is strange… would think that anything causing the core page to fail like that would be something wrong with the data for the core itself

**Comment by mardem1976** [comment]
Can echo the issues that [Arithmeticae](https://github.com/Arithmeticae) is seeing. Using Pocket Sync 4.0 on Mac with latest OS, SD card mounted directly on the Mac and fresh install with the final release of the core.

I actually got it to open the required window once with skip alternated unchecked, and clicked to download all. It was going painfully slow, so I decided to just leave it overnight. In the morning, it seemed to have locked up at 47%.

At that point I manually downloaded the remaining alt roms from archive.org and all is working fine on the Pocket.

**Comment by neil-morrison44** [comment]
This _might be_ improved by what I’m working on for 4.1 where the app is much smarter about filesystem stuff. Which’ll probably come early on in the new year since it’s a big change and I want to be fairly sure there’s not a whole load of new bugs.

For me it takes a not-unreasonable time (less than 5 minutes) to process all the alternative files & then works fine (downloading them in about an hour or so), but it is computing the hashes of multi-megabyte files for each one so that’s fairly intense.

I could change it to look at the modified time of the file instead, but that would be more error prone and it would mean we lose the app checking if the file has been downloaded ok.

**Comment by neil-morrison44** [comment]
Going to assume the 4.1 fix fixed this & close it off since there's not been any reports of similar since
