### ISSUE TITLE
Error when trying to open cores

### ISSUE THREAD

**Issue by volterrmore** [neil-morrison44/pocket-sync#182]
Object.hasOwn is not a function. (In 'Object.hasOwn(t,x.from)', 'Object.hasOwn' is undefined)
xye@tauri://localhost/assets/index-27990549.js:5670:1948719
o7@tauri://localhost/assets/index-27990549.js:38:77193
XI@tauri://localhost/assets/index-27990549.js:40:129778
jI@tauri://localhost/assets/index-27990549.js:40:125510
EW@tauri://localhost/assets/index-27990549.js:40:125438
Zg@tauri://localhost/assets/index-27990549.js:40:125291
N4@tauri://localhost/assets/index-27990549.js:40:121656
LE@tauri://localhost/assets/index-27990549.js:40:122460
LE@[native code]
Hu@tauri://localhost/assets/index-27990549.js:38:60934
@tauri://localhost/assets/index-27990549.js:40:119986

**Comment by neil-morrison44** [comment]
What OS version are you using?

**Comment by volterrmore** [comment]
3.10.1

**Comment by neil-morrison44** [comment]
That's the app version - what version OS are you using? (Like Windows 10 or MacOS 11)

**Comment by volterrmore** [comment]
My apologies, I'm using macOS Monterey Version 12.1 (21C52)

**Comment by volterrmore** [comment]
Just want to say thank you for helping me out and being so quick. I can update my mac os if that is the issue

**Comment by neil-morrison44** [comment]
That's the issue yeah (the app uses the OS's Safari on Mac) - MacOS 13/14 would definitely fix it, but the most recent 12 (12.7.1) might be enough

**Comment by volterrmore** [comment]
Okay, I'll go ahead and update it. I'll let you know how it goes. Thank you!

**Comment by volterrmore** [comment]
It's working great now thank you!

**Comment by remy** [comment]
@neil-morrison44 possible to polyfill `hasOwn` for backward support? I'm not super keen on upgrading the macOS to fix this because my machine is old…

**Comment by neil-morrison44** [comment]
@remy would probably work for `hasOwn`, but I'm not sure what else would be broken & it's hard to test on older MacOS versions so at some point it'll just be a blanket "not supported, sorry"

I'll chuck one in though since there's already a polyfill for `Array.at` & it doesn't look that complex to polyfill

**Comment by remy** [comment]
@neil-morrison44 if you're happy for me to send PRs to support it - and so long as it doesn't make anything any more complicated (i.e. limited to polyfills), I'm happy to do this.
