### ISSUE TITLE
MiSTer Sync broken?

### ISSUE THREAD

**Issue by dctrotz** [neil-morrison44/pocket-sync#183]
**Describe the bug**
MiSTer Sync does not work. I tried both on a Mac and Windows machine. From what I can gather, my mister install requires SFTP not just FTP and there is no way to indicate that. I am running a vanilla MiSTer install using the Mr Fusion script.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Saves -> MiSTer Sync 
2. Fill in the connection info
  a. It will say it is Connected!
4. Nothing works after this. I can select a save on the Pocket side but never on the MiSTer side, I don't even know what that screen looks like.

**Comment by neil-morrison44** [comment]
Does anything else appear in the log bit?

Are there saves on the MiSTer?

Are there saves on the Pocket?

**Comment by dctrotz** [comment]
<img width="1728" alt="Screenshot 2023-11-25 at 1 17 14 PM" src="https://github.com/neil-morrison44/pocket-sync/assets/5331672/9748ff9c-320b-4fe7-822e-1805dadc526e">
This is all I see. Sometimes the `Error: ftp_stream not active` message isn't there.
There are saves on the Pocket. 
There are saves on the Mister.

**Comment by neil-morrison44** [comment]
Hmm, seeing that after it saying it’s connected is definitely strange.

What says it’s SFTP only?
How recently was your MiSTer install created?

**Comment by dctrotz** [comment]
I might be wrong on that sftp only comment, but when I used other clients using ftp I can login but not browse. But if I use sftp it works fine.  I used the Mr fusion sdcard image to get things setup.

**Comment by neil-morrison44** [comment]
That’s strange - so other FTP clients work fine now but Pocket Sync still has the issue?

Not sure what would cause FTP to be able to login but not browse, but it looks like that’s the same issue that Pocket Sync is running into (where the stream becomes inactive after logging in but not in a way that’d get handled and send you back to the login)

**Comment by dctrotz** [comment]
Yes, other FTP clients work fine. How hard would it be to run Pocket Sync in a debugger? I might give that a try and see where the hang up is

**Comment by neil-morrison44** [comment]
If you have Rust installed you should be able to clone the repo, `npm i` then do `npm run tauri dev` to get the  app running in dev mode where it’ll output console messages / errors to the terminal.

Though -  anything interesting from the FTP side _should_ be being routed through to that log shown in the UI already so there might not be much extra.

**Comment by dctrotz** [comment]
I am not sure how much this helps but it dies in the `find_save_for` call on line 111 which leads to logging an Error on line 298 of the `save_sync_session.rs` file. The error is `Connection error: Connection refused (os error 61)`

**Comment by dctrotz** [comment]
Actually digging deeper, it is actually in the `list_platforms` call line 219. I do have a `/media/fat/saves` path on my MiSTer and I can connect and navigate it from other ftp clients.

**Comment by neil-morrison44** [comment]
Ah right, cool - good to know for anyone else who runs into that in the future
