### ISSUE TITLE
Object.hasOwn is not a function. (In 'Object.hasOwn(t,x.from)', 'Object.hasOwn' is undefined)

### ISSUE THREAD

**Issue by remy** [neil-morrison44/pocket-sync#184]
**Describe the bug**

Trying to update the NES core to 1.0.0 - I get `Object.hasOwn is not a function. (In 'Object.hasOwn(t,x.from)', 'Object.hasOwn' is undefined)` and a stack trace

**To Reproduce**

1. Go to Cores
2. Click on NES
3. See error - and now clicking on any tab generates the same error

<img width="1254" alt="SCR-20231124-oria" src="https://github.com/neil-morrison44/pocket-sync/assets/13700/cb4ce39b-4585-4d4f-9d93-a91274250943">

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.7.10
- Pocket Sync 3.10.1

**Comment by neil-morrison44** [comment]
Looks like the same issue as https://github.com/neil-morrison44/pocket-sync/issues/182

**Comment by remy** [comment]
Closing as duplicate! (Sorry, didn't spot the first instance).
