### ISSUE TITLE
Cores not loading on Mac

### ISSUE THREAD

**Issue by boosweats** [neil-morrison44/pocket-sync#187]
Hi. I have received this error message every time I click on a Core image to try and install. Please help.

Cores: Spiritualized.GBA
Object.hasOwn is not a function. (In 'Object.hasOwn(t,x.from)', 'Object.hasOwn' is undefined)
xye@tauri://localhost/assets/index-27990549.js:5670:1948719
o7@tauri://localhost/assets/index-27990549.js:38:77193
XI@tauri://localhost/assets/index-27990549.js:40:129778
jI@tauri://localhost/assets/index-27990549.js:40:125510
EW@tauri://localhost/assets/index-27990549.js:40:125438
Zg@tauri://localhost/assets/index-27990549.js:40:125291
N4@tauri://localhost/assets/index-27990549.js:40:121656
zI@tauri://localhost/assets/index-27990549.js:40:120605
zI@[native code]
M@tauri://localhost/assets/index-27990549.js:25:10718
Q@tauri://localhost/assets/index-27990549.js:25:11086

I am using a Mac with OS 12.2.1 and Pocket Sync v3.10.1

**Comment by neil-morrison44** [comment]
Same issue as https://github.com/neil-morrison44/pocket-sync/issues/182 fix for it should be going out with the next release (should be within a week) - but MacOS 12 is technically unsupported

**Comment by boosweats** [comment]
I have a friend who has OS 13 and says it works fine. Is this just a specific OS 12 issue?

**Comment by neil-morrison44** [comment]
Yeah - the link in my last comment goes into a bit more detail on it
