### ISSUE TITLE
Request: Update All Cores + Required Files

### ISSUE THREAD

**Issue by seajaysec** [neil-morrison44/pocket-sync#199]
**Is your feature request related to a problem? Please describe.**
My loop of using Pocket Sync is viewing updatable cores, clicking each one by one, clicking Update once I'm in the core details, checking if there are any new required files, updating those, clicking Back to list, and repeating for like 30 minutes. I just had to do this for 55 cores, and that's pretty common to do once or twice a month.

**Describe the solution you'd like**
In the top row of the Cores menu add a button that updates all cores and required files. It should inherit the global setting for including alternate files.

**Describe alternatives you've considered**
If you set up an API for the app I could just do this myself, but that seems like considerably more work on your part.

**Additional context**
I love Pocket Sync, this is the only thing that holds me back from recommending it to others.

**Comment by neil-morrison44** [comment]
Yeah - I want to put _something_ in for this now that there’s all the Jotego cores and they quite often get updates all at once

**Comment by neil-morrison44** [comment]
I think how I want to do this is:

- A button on the cores index screen that opens a modal which shows a list of cores which have updates
- Each core shows its name and its platform, its platform image, and category.
- Each core has 3 checkboxes (Update, Required Files, Replace Platform Data)
- Cancel & Begin buttons at the bottom
- As it goes through the cores it shows which one is being updated, along with the donation links & the release notes (if applicable)
