### ISSUE TITLE
Linux DEB - Error loading shared library - libssl

### ISSUE THREAD

**Issue by Melluish** [neil-morrison44/pocket-sync#2]
Linux Mint 21 Cinnamon

Get this when running:

```
pocket-sync: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

I have the package `libssl-dev` installed which I thought should satisfy that dependency.

**Comment by neil-morrison44** [comment]
Looks like it’ll be this: https://github.com/tauri-apps/tauri/issues/4470

I’ll try the suggested workarounds in the app - sounds like there’s the `lsb` workaround on the user side if you want to give that a shot

**Comment by Melluish** [comment]
That didn't work for me unfortunately but the AppImage is working fine. Thanks.
