### ISSUE TITLE
Pocket Sync empty page on MAc

### ISSUE THREAD

**Issue by EvanKly** [neil-morrison44/pocket-sync#201]
Hey,

Just trying emulation on my new analog pocket. I've downloaded the latest Pocket sync dmg for my mac [Pocket.Sync_3.11.2_universal.dmg](https://github.com/neil-morrison44/pocket-sync/releases/download/v3.11.2/Pocket.Sync_3.11.2_universal.dmg)

Once I open it, I have a blank page with no content. I have Mac OS Big Sur and an M1 chip.
Any idea what's the issue?
Thank you very much 

<img width="928" alt="Capture d’écran 2023-12-09 à 23 31 46" src="https://github.com/neil-morrison44/pocket-sync/assets/31880540/08676716-ac70-4bff-bc9e-d9987cbb9bd1">

**Comment by neil-morrison44** [comment]
Big Sur isn’t supported - https://github.com/neil-morrison44/pocket-sync#why-doesnt-this-work-on-older-macos-version

There’s some support for Monterey, but there might be issues.

**Comment by EvanKly** [comment]
Oh ok great to know, thank you for your quick reponse!
