### ISSUE TITLE
Customize the path of the FTP server destination when using MiSTer FPGA sync

### ISSUE THREAD

**Issue by SpazShark** [neil-morrison44/pocket-sync#208]
I've just got my new Analogue Pocket and am thrilled to see your software and the sync feature with MiSTer saves!

Right now it appears that there is a hard-coded path of **//IP_of_MiSTer/fat/media/saves**. I don't see how this can be changed.

In my case I have my MiSTer saves sync'd to a file share (using the CIFS_mount.sh script) and it's located at **IP_of_HomeServer/MiSTer/saves**. I'd love it for the saves to able to be sync'd here instead of the MiSTer directly. That way I don't have to turn on my MiSTer every time to sync the files.

Is this possible to add?

**Comment by neil-morrison44** [comment]
Yeah, that should probably be easy enough to add in as an “advanced” option under the login bit I think.

Does it currently work with the MiSTer turned on since the MiSTer mounts the remote share as `fat/media/saves`?

**Comment by SpazShark** [comment]
Yes it works perfectly now as I think that the Mister symlinks the directory to ensure compatibility. The only inconvenience (and it's minor) is that I have to turn on the Mister first.

**Comment by neil-morrison44** [comment]
Having an issue clean up - going to close this one off as not planned, I think the amount of people using the MiSTer sync is already pretty low so I'm hesitant to add more codepaths to it which could introduce bugs which'd go unnoticed for a while

**Comment by SpazShark** [comment]
No problem! Thanks again for a great sync solution!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
