### ISSUE TITLE
Can not load

### ISSUE THREAD

**Issue by neogeo81** [neil-morrison44/pocket-sync#21]
See screenshot
<img width="912" alt="Bildschirmfoto 2022-12-05 um 16 33 14" src="https://user-images.githubusercontent.com/32906058/205677299-cddbf1a1-90c2-4e80-bff7-a045c0c9de3a.png">

**Comment by neil-morrison44** [comment]
Sounds like there's some unspecified network problem connecting to either the core inventory or the github release page, does this happen every time the app's loaded?

**Comment by neogeo81** [comment]
No, it worked great the last time. Only since today.

Neil Morrison ***@***.***> schrieb am Mo., 5. Dez. 2022,
20:09:
