### ISSUE TITLE
Parse error in JSON input

### ISSUE THREAD

**Issue by Kugelblitz360** [neil-morrison44/pocket-sync#215]
For several cores, whenever I try the "Settings" button, I receive this:

> Cores: Spiritualized.2600
> Cores/Spiritualized.2600/interact.json 
>  Parse error in JSON input:
> {    "interact": {...
> Expected double-quoted property name in JSON at position 370 (line 19 column 6)
> SyntaxError: Cores/Spiritualized.2600/interact.json 
>  Parse error in JSON input:
> {    "interact": {...
> Expected double-quoted property name in JSON at position 370 (line 19 column 6)
>     at JSON.parse (<anonymous>)
>     at B (https://tauri.localhost/assets/index-mwYJ_dGW.js:60:366)
>     at Object.de [as parse] (https://tauri.localhost/assets/index-mwYJ_dGW.js:60:859)
>     at aa (https://tauri.localhost/assets/index-mwYJ_dGW.js:60:1120)

The JSON file looks perfectly legal to me, no idea what causes this.

Thanks for the nice tool!

**Comment by neil-morrison44** [comment]
I believe the spiritualized core has an extra `,` on the line before the one the linter is pointing to.

Annoyingly the Pocket itself is quite forgiving when it comes to JSON - more so than most built in JSON parsers.

You can try opening an issue on the GitHub page for the core, but it's unlikely to get fixed

**Comment by Kugelblitz360** [comment]
Yep, that fixed it. Thanks!
