### ISSUE TITLE
Pocket Sync throws error when scrolling through "Games" and "Core" list if Jotego's Neo Geo Pocket core is installed

### ISSUE THREAD

**Issue by Missingno255** [neil-morrison44/pocket-sync#222]
If the JTNGP core is installed pocket sync will throw this error if it is installed.

Cores: null
Attempt to read platform_id jtngp
Error: Attempt to read platform_id jtngp
    at https://tauri.localhost/assets/index-jbO2GQHe.js:4766:13476

Reproduceable by having the core installed and attempting to scroll though "Games" and "Cores" sections
Not sure if it's something I missed or it's not on my end.

**Comment by neil-morrison44** [comment]
Looks like you're somehow missing the `Platforms/jtngp.json` file - once it's there it should be fine

**Comment by Missingno255** [comment]
Yep, it worked! It was a bug on my end. Thanks!
