### ISSUE TITLE
Stuck loading screenshot on macOS

### ISSUE THREAD

**Issue by akira28** [neil-morrison44/pocket-sync#23]
On macOS 12.6.1 when I open a screenshot the app show the loading animation indefinitely. Pocket-sync Version 1.4.1 (20221206.003950). There's no debug console, so I cannot share an eventual js error

<img width="869" alt="image" src="https://user-images.githubusercontent.com/996257/205993996-224d1836-8c6f-4e17-b680-41936c946e52.png">

**Comment by neil-morrison44** [comment]
What core's the screenshot for? Is the core still installed?

**Comment by akira28** [comment]
it's a screen from the gameboy camera cartridge, using the native gb core

**Comment by neil-morrison44** [comment]
Ah yeah, I forgot about games that use the cartridge cores.

Might be a similar problem with cartridge save states, I'll see about fixing both.
