### ISSUE TITLE
Grey screen still shows when updating cores.

### ISSUE THREAD

**Issue by apadders** [neil-morrison44/pocket-sync#230]
When updating multiple cores the app still displays a grey screen and then I have to restart the app. It happens if I update manually or using the update all option.

It happens if remove duplicate existing files is ticked or unticked.

I have the latest 4.3.0 installed and removed previous application data beforehand.

**Comment by neil-morrison44** [comment]
There might be something interesting in the logs for this now - there's a button at the bottom of the `Settings` page that'll open the folder with the log in it, if you could comment with it here it'll probably point to the issue

**Comment by shazbot711** [comment]
I am having a similar issue. Attached are my logs
[Pocket Sync.log](https://github.com/neil-morrison44/pocket-sync/files/14068372/Pocket.Sync.log)

**Comment by neil-morrison44** [comment]
@shazbot711 thanks for that!
Unfortunately - nothing out of the ordinary in the log

**Comment by neil-morrison44** [comment]
Have a go with v4.3.1, it should collect more useful logs than v4.3.0 did

**Comment by shazbot711** [comment]
[Pocket Sync.log](https://github.com/neil-morrison44/pocket-sync/files/14089471/Pocket.Sync.log)
Here are the new logs with the new version. Same thing happening, specifically when trying to do anything within a core.

**Comment by neil-morrison44** [comment]
@shazbot711 nothing too useful in that log either - what OS etc are you using?

**Comment by shazbot711** [comment]
Windows 10

**Comment by apadders** [comment]
> Windows 10

I am on Windows 11 22H2 22621.3007. I will do logs when there's a new core update.

**Comment by neil-morrison44** [comment]
@apadders the "Update Core" button _should_ do the same thing even when there isn't an update available, it's just replace the files with identical copies.

Or you could drop one of these zips over the app & it'll install the old version which would then show up as needing an update https://github.com/budude2/openfgpa-GBC/releases/tag/v1.0.5

(just incase the next core updates are ages away - there'll probably be JOTEGO ones on friday though)

**Comment by apadders** [comment]
> @apadders the "Update Core" button _should_ do the same thing even when there isn't an update available, it's just replace the files with identical copies.
> 
> Or you could drop one of these zips over the app & it'll install the old version which would then show up as needing an update https://github.com/budude2/openfgpa-GBC/releases/tag/v1.0.5
> 
> (just incase the next core updates are ages away - there'll probably be JOTEGO ones on friday though)

[Pocket Sync.log](https://github.com/neil-morrison44/pocket-sync/files/14117899/Pocket.Sync.log)

Just tried updating a few cores one at a time. Asteroids work and then grey screen. Also Donkey Kong updated but then grey screen. Amiga core did update okay and return to application. Unfortunately when it grey screens not much is logged to the log file. When the Amiga core updated fine there was more logging info the log file.

**Comment by neil-morrison44** [comment]
Hmmm, yeah - not much use in a log that can't log the errors.

Thanks for trying - I'll have a go to see if I can replicate it

**Comment by apadders** [comment]
Great job, thanks. Works fine now.
