### ISSUE TITLE
v4.3.0 Crashes While Updating Cores

### ISSUE THREAD

**Issue by JeffHochberg** [neil-morrison44/pocket-sync#231]
**Describe the bug**
I've tried updating the cores on my Pocket three times. Each time, the update process gets to the second or third core that needs to be updated, then the application closes abruptly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch PocketSync and click Connect - then browse to the drive letter for the Micro SD card
2. Click on Cores & add a checkmark in the Updatable section at the top of the window
3. Click Update All
4. Application starts updating cores, then crashes

**Expected behaviour**
I would expect the cores to update without issue. That's been my experience with previous versions of PocketSync.

**Screenshots**
Difficult to screenshot

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11 (Version 10.0.22621.3007)

**Additional context**
I'd be happy to collect any logs that may be helpful.

**Comment by neil-morrison44** [comment]
Which core is it crashing on?

if you go into settings & scroll to the bottom you can access the folder with the logs in it and copy them here

**Comment by neil-morrison44** [comment]
Have a go with v4.3.1, it should collect more useful logs than v4.3.0 did
