### ISSUE TITLE
Pocket Sync won't self-update (Windows)

### ISSUE THREAD

**Issue by espiox** [neil-morrison44/pocket-sync#237]
When a new update is released, Pocket Sync asks to update, and runs the installer. But when it re-opens, it's the previous version and prompts to install the new update again, and there are two versions listed in Windows insatalled apps list - my originally installed version and the update. 

It's been doing this for a while so I finally decided to uninstall both versions and do a fresh re-install, but with the new 4.4 update it's still doing it, and again there are two versions appearing:
![image](https://github.com/neil-morrison44/pocket-sync/assets/60354147/369650d9-2a6f-4c1e-82de-fa4f92ab4ed7)

(I'm on Windows 11, version 22H2)

**Comment by neil-morrison44** [comment]
That’s annoying - I’m just using the default auto-updater from Tauri so I’ll see if they have any known issues around that.

**Comment by neil-morrison44** [comment]
@espiox do you know what the actual name / file path of the downloaded & existing app is?

Think that might help work out what’s going wrong

**Comment by espiox** [comment]
I installed it to the default directory: "C:\Users\espio\AppData\Local\Pocket Sync" - this is the version that the Start Menu etc is pointing to.

However it looks like the updater is installing a copy to "C:\Program Files\Pocket Sync" instead.

**Comment by neil-morrison44** [comment]
That could be it - sounds like the updater is using the `.msi` which installs it to one place (presumably program files) vs the `.exe` that installs it to the other.

And both the `.exe` & `.msi` installers are attached to the release for some reason

**Comment by espiox** [comment]
Ah, that makes sense, I usually go for the .exe option for a new install. I've done a fresh install to Program FIles from the .msi, hopefully that'll solve the problem next time there's an update.

**Comment by neil-morrison44** [comment]
I'm trying to fix this in v4.5.0 so there's only one option for windows (the exe / nsis one). Will close this off if I manage to get it working

**Comment by neil-morrison44** [comment]
I _believe_ this should be fixed now (it might even automatically move people over who were using the WiX / `.msi` version but I don't know for sure yet)

**Comment by neil-morrison44** [comment]
@espiox have you had a chance to try v4.5.0 yet? 

There's someone on the subreddit for who the installer's completely broken on Windows 10 now & I'm trying to work out how busted it is in Windows generally.

**Comment by espiox** [comment]
I updated to 4.5 last night and everything worked fine.
