### ISSUE TITLE
Fetch setup: buttons become unreachable due to non-scrollable UI

### ISSUE THREAD

**Issue by f00b4r0** [neil-morrison44/pocket-sync#245]
**Describe the bug**
When setting up an Internet Archive fetch, the "Close" and/or "Add fetch" buttons may become unreachable as they are pushed outside of the window visible area. This part of the UI (an overlay?) is not scrollable (at least on macOS) and thus if the main window can't be made "tall enough" the only way out is to quit the software (since e.g. typing "Esc" doesn't trigger "Close").

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Fetch
2. Click on Add new Fetch
3. Select Internet Archive fetch
4. Enter field data and extension filters
5. Observe problem

**Expected behaviour**
The Add new fetch UI should probably be scrollable for this use case where the content can vary in length arbitrarily (depending on e.g. the number of extension filters setup).

**Screenshots**
![screen1](https://github.com/neil-morrison44/pocket-sync/assets/23039782/e39fc7d3-35a7-4241-aa9d-d0d9a731cf85)
![screen2](https://github.com/neil-morrison44/pocket-sync/assets/23039782/04df6c5a-b7f9-4d66-9a6d-9a480a0d88c3)

This may or may not be related but the default scaling of the welcome screen is also off on my system: the bottom "updates" section is always truncated, no matter the size of the window at launch:
![wecome](https://github.com/neil-morrison44/pocket-sync/assets/23039782/8af51a35-22ab-4161-b2cb-1b7297d22163)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.7.3

**Comment by neil-morrison44** [comment]
Yeah I've also noticed that issue with the newsfeed - though it always seems to fix itself without any user input after a minute or so, which is a particularly annoying thing for a bug to to.
