### ISSUE TITLE
Error when getting ImagePacks

### ISSUE THREAD

**Issue by palla89** [neil-morrison44/pocket-sync#248]
**Describe the bug**
Platforms: null
undefined is not an object (evaluating '(await(await fetch(`https://api.github.com/repos/${t}/${e}/releases/latest`)).json()).assets.find')
@tauri://localhost/assets/index-Rcqo1cnm.js:4763:14279

**To Reproduce**
Platforms -> Image packs

**Desktop (please complete the following information):**
- Mac OS Sonoma 14.1.2
 - Version 4.5.1

**Comment by neil-morrison44** [comment]
@palla89 does this happen again if you close the app & retry?

I _think_ the only thing that would cause this is loading the app in the brief period between an image pack release getting created and the .zip being attached.

The Image Pack & Data Pack buttons seem to work for me just now

I'll put in a fix that ignores that particular pack if it doesn't have assets
