### ISSUE TITLE
NES core install failed and reported an error

### ISSUE THREAD

**Issue by chasemcardle** [neil-morrison44/pocket-sync#264]
**Describe the bug**
Installing the NES core failed. This is my first ever core to try and install on a new SD card.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Cores'
2. Click on 'NES'
3. Follow on screen prompts

If the error only appeared after installing a certain core or image pack say which one.

**Expected behaviour**
I expected the core to install correctly.

**Screenshots**

**Logs**
[Pocket Sync.log](https://github.com/neil-morrison44/pocket-sync/files/14793725/Pocket.Sync.log)

Cores: agg23.NES
Cores/agg23.NES/core.json 
 Parse error in JSON input:

Unexpected EOF
parse@[native code]
P@tauri://localhost/assets/index-C6kz_0x2.js:63:364
@tauri://localhost/assets/index-C6kz_0x2.js:63:1116

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version 14.4.1

**Additional context**
Using SD via USB mode on the analogue pocket
Pocket FIrmware 2.2

**Comment by chasemcardle** [comment]
SNES Reports the same issue

[Pocket Sync.log](https://github.com/neil-morrison44/pocket-sync/files/14793777/Pocket.Sync.log)

Cores: agg23.SNES
Cores/agg23.SNES/core.json 
 Parse error in JSON input:

Unexpected EOF
parse@[native code]
P@tauri://localhost/assets/index-C6kz_0x2.js:63:364
@tauri://localhost/assets/index-C6kz_0x2.js:63:1116

**Comment by chasemcardle** [comment]
I do not get the errors when connecting to the SD card using an SD Card slot

**Comment by neil-morrison44** [comment]
Hmmm, yeah - from the log it looks like it tried to read the file about the core before it had finished writing it.

Unfortunately my Pocket's SD-over-USB drive functionality has never worked so I haven't seen these sorts of issues.

There's a fix I've been planning to get in to stop it re-scanning the game assets as it installs them that'd also potentially help with this, but using the SD card directly is always going to be the best experience

**Comment by neil-morrison44** [comment]
I _think_ the problem you ran into here where it tried to read the files for the core before they were written should be resolved by v4.9.0, though it seems to be very rare
