### ISSUE TITLE
Ignore platform files by default when upgrading

### ISSUE THREAD

**Issue by espiox** [neil-morrison44/pocket-sync#268]
Any chance that you could add a setting to always ignore Platform data/images when updating a core (either single or batch updating)? I just lost some customisation because I forgot to toggle it off.

Obviously when installing a new core it's fine, but once I've got one installed I basically never want an update to touch those files.

**Comment by neil-morrison44** [comment]
Yeah - I think that's a good idea, it'll need to know if the file exists already when doing an install / update but I _think_ that's fine too

**Comment by espiox** [comment]
Fantastic, thank you 🙏🏻
