### ISSUE TITLE
Feature request: ROM syncing

### ISSUE THREAD

**Issue by MaddoScientisto** [neil-morrison44/pocket-sync#27]
I'm requesting a feature that would allow syncing the whole roms library with a local folder on the pc.

Ideally it would be possible to choose a different folder for each system but also a global folder could work, as long as the resulting folder structure is generic enough to be compatible with other emulators or syncing apps

**Comment by neil-morrison44** [comment]
I was thinking about this while doing the first MiSTer save file syncing version, I've avoided it so far for a few reasons:

- there's multiple ROM structure formats I'd need to go between (Pocket, MiSTer, retroarch etc)
- I'd need to do some transformations like the MiSTer ROMs are recommended to be .zip files but the pocket can't handle those + any differences in headers (which I think has mostly gone away now)
- there's dozens of ways people like to keep their ROMs organised, don't really want to clobber someone's folder structure accidentally with some badly done code
- to do it properly it'd need to sync with MiSTer over FTP & know what all the core names translate as (which I had for the save stuff but still, it's a lot)


I was trying to think of some sort of "plugin" system to negate a lot of these things, or to try and better integrate with some ROM management tool people were already using, but that's a whiles away

**Comment by neil-morrison44** [comment]
Going to close this one off until I think of how to really do it well (ideally in a way that integrates with something that already does it really well)
