### ISSUE TITLE
macOS app is not signed

### ISSUE THREAD

**Issue by kana-sama** [neil-morrison44/pocket-sync#278]
I want to create `homebrew` cask for pocket-sync, but it requires signature.

**Comment by neil-morrison44** [comment]
Hi, to sign the app I'd need to be paying for an Apple Developer Account indefinitely (ad-hoc would likely work for brew but Tauri doesn't support it in the CI, I believe).

Also I'm not interested in supporting another distribution method with its own quirks (e.g. would need to know not to deactivate the built in auto-update etc). Flatpak on the linux side already has issues all of its own
