### ISSUE TITLE
alphamission core can't be installed ("Unable to download ZIP: 404 Not Found")

### ISSUE THREAD

**Issue by tarikalmashni** [neil-morrison44/pocket-sync#279]
The title basically says it all. When hitting the install button, I'm getting a popup message saying

**Unable to download ZIP:
404 Not Found**

![image](https://github.com/neil-morrison44/pocket-sync/assets/63227497/ca8a4f03-1ece-4b10-8efe-60e224601d2e)

**Comment by tarikalmashni** [comment]
Update: Turns out it has already been installed (maybe in the background without the GUI noticing it). Now it's among the installed cores.

**Comment by neil-morrison44** [comment]
Having an issue cleanup - this seems to work for me now & no one else has reported similar issues. I'm guessing it was a brief problem with getting the core's zip from GitHub or something else strange.
