### ISSUE TITLE
[Bug] Platform Images does not include Shissa43 platform images

### ISSUE THREAD

**Issue by pyonghe** [neil-morrison44/pocket-sync#285]
While attempting to change the platform images of a console/arcade in the Platforms tab, the preview of the platform images from Shissa43 was not shown. 

E.g, In this case I am viewing the Alpha Mission Arcade plaform page. 

![image](https://github.com/neil-morrison44/pocket-sync/assets/7576046/0bdd0114-59fb-4939-9196-d56abad9a2e4)

We can see that the images from Shissa43 was not shown in the preview mode for user to select. Upon looking at the source of pocket sync, 

I understand that these previews are downloaded from the list provided by mattpannella via the source

https://github.com/neil-morrison44/pocket-sync/blob/eb3236718dad0e89e68ae7f8df9b1fb010ae48d7/.github/workflows/scripts/build_platforms_zip.ts#L19

, thru [here](https://raw.githubusercontent.com/mattpannella/pocket-updater-utility/main/image_packs.json), and hosted [here](https://neil-morrison44.github.io/pocket-sync/platforms.zip)

While unzipping the contents of the platforms.zip, I do not see the contents for Shissa43 platform images, as shown below, 

![image](https://github.com/neil-morrison44/pocket-sync/assets/7576046/66c3d86d-dbb8-4822-8000-e5feca0e87cc)

Not sure if this is reported, but would like to be able to see those images before applying to the platforms.

**Comment by pyonghe** [comment]
A suggestion would be to give an option to users, to allow them to specify the platform images folder that they have or to use the one you are hosting.

**Comment by neil-morrison44** [comment]
Looks like the underlying cause of this is that Matt's JSON no longer matches the names of the download assets: https://github.com/Shissa43/Analogue-Pocket-Platform-Art/releases/tag/v0.2.7
