### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by SupaDude1** [neil-morrison44/pocket-sync#289]
What if you could put your video files onto your analogue pocket. Hear me out, the analogue pocket has a 1080p display so you can watch just about any movie, video, or show you want. Just make a core that maps each button to do something like A=pause/unpause, right trigger=fast forward, left trigger= rewind

I just want to watch movies in 1080p on my analogue pocket

**Comment by neil-morrison44** [comment]
Your best bet is to look into something like the GBA video, but that’s low bitrate & resolution & frames per second.

I believe, in theory, someone could do a DVD player core - but I doubt there’s much interest in it from core developers & I’m not sure the MPEG decoder would fit.

That’d need to happen before this app could do anything with them
