### ISSUE TITLE
Every Tab Says Null.

### ISSUE THREAD

**Issue by FiSHHeAD13** [neil-morrison44/pocket-sync#294]
Every tab under my Pocket Sync is saying null and or 
Error: Attempt to read platform_id mega_duck
    at https://tauri.localhost/assets/index-Dk-urbvo.js:4951:13530

I am not smart enough to understand or fix this problem. I just want to download games on my Pocket.

I've tried reinstalling the Pocket sync. It just wont work.

**Comment by neil-morrison44** [comment]
Have you got a screenshot of what it’s doing?

If you delete the mega duck core folder that might clear it, looks like some file is corrupt or something

**Comment by kitchentongue** [comment]
Getting this error when trying to load any specific core. Just trying to enable the new visual filter :(
Regardless of what core, it always reads 
Invalid regular expression: invalid group specifier name
RegExp@[native code]
_p@tauri://localhost/assets/index-CM7525Ey.js:52:17044
r@tauri://localhost/assets/index-CM7525Ey.js:42:4604
ap@tauri://localhost/assets/index-CM7525Ey.js:52:13453
g_@tauri://localhost/assets/index-B3ZZMOkK.js:39:17021
Ww@tauri://localhost/assets/index-B3ZZMOkK.js:41:44047
Vw@tauri://localhost/assets/index-B3ZZMOkK.js:41:39779
X2@tauri://localhost/assets/index-B3ZZMOkK.js:41:39707
ch@tauri://localhost/assets/index-B3ZZMOkK.js:41:39559
yg@tauri://localhost/assets/index-B3ZZMOkK.js:41:35923
Uw@tauri://localhost/assets/index-B3ZZMOkK.js:41:34872
Uw@[native code]
E@tauri://localhost/assets/index-B3ZZMOkK.js:26:1551
oe@tauri://localhost/assets/index-B3ZZMOkK.js:26:1914

**Comment by Threeethan** [comment]
I'm hitting the same thing that kitchentongue just posted - it popped up during a core update. 

Here's a screenshot:
<img width="1163" alt="Screen Shot 2024-09-11 at 10 27 24 PM" src="https://github.com/user-attachments/assets/e4ca8c11-4aa3-40d1-83d2-7f8b4932c9c4">

This comes up when loading clicking to load any core - if I navigate to any other tab and hit "retry" it clears the error, but then if I return to "Cores" and click any core (installed or not) this pops back up. I cleared the cache, no change.

**Comment by neil-morrison44** [comment]
@kitchentongue @Threeethan looks to be a different issue, can you open a new issue & let me know your OS version etc?

Also good to know _which_ core was updating at the time it started

**Comment by kitchentongue** [comment]
I think it may be the same issue, as it's happening on every tab outside of the Cores as well. Everything just registers as "null" as the OP of this issue describes

**Comment by neil-morrison44** [comment]
It’s the error being different that means it’s a different issue with the same result - the OP was just missing a platform json file vs something going wrong with regexes
