### ISSUE TITLE
Atari 2600 & ColecoVision Games Not Being Recognized

### ISSUE THREAD

**Issue by ZReport** [neil-morrison44/pocket-sync#3]
Atari 2600 & ColecoVision games not being recognized within the UI. 

![2600](https://user-images.githubusercontent.com/12631557/203218154-00dd5e94-a377-4810-bb87-49f735beea31.png)

**Comment by ZReport** [comment]
Sounds like a plan to me!  Looks like every other core is working well enough with the listing so far!

**Comment by neil-morrison44** [comment]
Worked it out - those cores don't specify _which_ file extensions to look for since they must be happy dealing with whatever I guess

I'll get a fix in that also removes the bios files from the count & creates the folder if it's missing
