### ISSUE TITLE
PDM:Trojan.Win32.Generic.nblk detected when trying to update your app

### ISSUE THREAD

**Issue by Melabones** [neil-morrison44/pocket-sync#301]
App prompted update and I excepted the update then it was flagged as a PDM:Trojan and was removed

**Comment by neil-morrison44** [comment]
That’s a false positive, they happen sometimes for unsigned apps (and signing an app still costs loads).

All the code’s up on this github & it gets built automatically by github & you can even build it yourself.

You’ll probably need to re-download & reinstall
