### ISSUE TITLE
Corrupt file

### ISSUE THREAD

**Issue by Alblooki2005** [neil-morrison44/pocket-sync#302]
pocket sync says (the file or directory is corrupted and unreadable. (is error 1392)). 

Steps to reproduce the behaviour:
1. Plugged my analogue pocket through usb to access sd with pocket sync. 
2. Edited the name and year of some arcade cores. 
3. Some of them showed that there are missing files so I went and downloaded them but after completion it showed beside it unkonw. 
4. Unplugged analogue pocket and when I entered open fpga it said loading as usual but when I try to enter and category it returns me to the main menu. 

Note pocket sync can access firmware, palettes, platforms, save states, saves, and screenshot but not games and cores.

Tried it for 1 core before doing several and it work pretty well and at that time I didn't download any missing files. 

I got windows 11.

**Comment by neil-morrison44** [comment]
I’d recommend plugging the SD card in directly & doing a reformat.

You might be able to find which file / folder is corrupted in File Explorer & delete that specific file / folder.

What likely happened is some sort of error of the Pocket’s USB connection or an SD card issue

**Comment by Alblooki2005** [comment]
Thank you very much, could I know wich one exactly through the logs?

**Comment by neil-morrison44** [comment]
Don’t think so, you’ll just see that it’s trying to open games / cores.

Can _probably_ narrow it down to something in the `Cores` folder with it crashing on both Cores & Games, but it’d be safer to copy out the `Saves` & `Assets` folder and reformat the card.
