### ISSUE TITLE
Keep custom image and name when updating cores

### ISSUE THREAD

**Issue by fabianmossberg** [neil-morrison44/pocket-sync#304]
I find it very annoying that my renamed cores, and custom images gets reset when updating cores.

I would love if there was an option to keep the custom name and image pack chosen for the cores when updating them.

**Comment by neil-morrison44** [comment]
There should be a `Don't Replace Platform Files During Updates` option in Settings already which'll set both update methods (per-core & Update All) to not change those files by default

**Comment by fabianmossberg** [comment]
Oh, there it was! And it was unchecked on mine for some reason.
