### ISSUE TITLE
Suggestion for ordering Screen Filters

### ISSUE THREAD

**Issue by syltendo** [neil-morrison44/pocket-sync#311]
I love the ability to only pick and choose screen filters per core. One possible improvement and something I'd like to see would be the ability to sort those filters, organize the order they appear (per core) in the options. Possibly using drag and drop.

For example, some may want to put the respective handheld filters before the Trinitron one for handheld cores, or sort out filters by hardware date of release (GB, Lynx, NGP, GBA,...), or whatever else.

**Comment by neil-morrison44** [comment]
Oh that's interesting, I didn't even notice they're sortable but that makes sense.

You _might_ be able to get this just now by toggling them all off then toggling them on in the order you want them to appear, but that's pretty awkward.

**Comment by neil-morrison44** [comment]
I'll just tack it on to here but the list should also limit the number of selected display modes to 16 - show a warning and / or prevent a 17th from being selected

**Comment by neil-morrison44** [comment]
Was looking at ways to get this in, but unfortunately Tauri's file drop functionality breaks HTML5 drag & drop (https://github.com/tauri-apps/tauri/issues/3277) so it'd mean I'd need to choose between being able to re-order the Display Modes nicely & being able to drag and drop zip files...

Discovered that after I'd put in 2 iterations of the dragging functionality.
I've got it on a branch incase Tauri is able to support both in the future, but I'm going to put the warning in about having more than 16 display modes selected & close this as not planned.
