### ISSUE TITLE
4.12.0 - Setting display modes leads to unnecessary scrolls and vanishing options

### ISSUE THREAD

**Issue by Kugelblitz360** [neil-morrison44/pocket-sync#314]
So I tried to setup the new video modes and clean up stuff. One annoyance and one bug:

a) Every time I click on a video mode to toggle, the screen jumps to the top again and I need to scroll down

b) After toggling five modes, ALL modes vanish from screen, the partition stays empty. Happened to me on the Lynx core when I tried to deselect all but the Lynx modes for it. Had to restart twice.

Thanks, Boris

**Comment by neil-morrison44** [comment]
I’ve been looking at ways to remedy A as part of the V5 branch, so that should (hopefully) be improved as part of that.

B I’ve not seen before, but I’ll keep an eye out for it.
