### ISSUE TITLE
Scrolling in the menu "Does" or "Games" results in an Error on macOS Sonoma 14.6.1

### ISSUE THREAD

**Issue by Bonewire** [neil-morrison44/pocket-sync#317]
**Describe the bug**
If I scroll in the menu Cores or Games I can only scroll to a few cores. Suddenly an Error window appears (see screenshot).
The same happens when I try to chose "Category: handheld" for example.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Cores
2. Scroll down with your mouse wheel
3. Error window appears

**Desktop (please complete the following information):**
 - OS: MacOS
 - Sonoma 14.6.1

[Pocket Sync.log](https://github.com/user-attachments/files/17003897/Pocket.Sync.log)
<img width="1004" alt="SCR-20240914-updu" src="https://github.com/user-attachments/assets/9865016e-6848-4fc9-b2fb-beeb9533e17c">

**Comment by neil-morrison44** [comment]
Looks similar to https://github.com/neil-morrison44/pocket-sync/issues/294

I think you're _probably_ missing the file which should be in `Platforms/jailbreak.json`, now sure how / why it's missing though. 

If you grab the file from the zip for the release here https://github.com/rolandking/openFPGA-jailbreak/releases/tag/v1.1 and put it where it's meant to go that should get things working again.

**Comment by Bonewire** [comment]
That worked. Thank you so much for the fast response. What is putting that missing file there in the first place? Is it part of the firmware itself? Does pocket sync put it there?

**Comment by neil-morrison44** [comment]
Whatever app you installed the Jailbreak core with _should_ have put it there, I'm not sure why they sometimes get missed.
Did you install the jailbreak core with Pocket Sync without turning off any of the files in the install prompt?

I'm planning on putting some sort of "attempt repair" button in to the error page at some point when it can tell that a file's just missing like this.

**Comment by Bonewire** [comment]
Ah ok. Thank you for helping me. And thanks for your hard work on this great tool.
