### ISSUE TITLE
Kaspersky antivirus is flagging pocket sync as dangerous

### ISSUE THREAD

**Issue by joaquincoelho** [neil-morrison44/pocket-sync#321]
Hi there,

Kaspersky antivirus is flagging Pocket Sync 4.12.4 as a virus. I've attached a couple of screenshots.

![image](https://github.com/user-attachments/assets/39f21f44-5a57-4bca-af2d-cddb4d298fef)
![image](https://github.com/user-attachments/assets/0612a907-dc40-4525-b179-648d4a828b57)

**Comment by neil-morrison44** [comment]
Yeah, false positives happen sometimes.
All the code to Pocket Sync is public & it’s built publically too.

from the screenshot it looks like your antivirus is also detecting chrome as a virus
