### ISSUE TITLE
Error When Opening Games and Cores Tab

### ISSUE THREAD

**Issue by Mr-GOJIRA-san** [neil-morrison44/pocket-sync#325]
**Describe the bug**
Hi, this is my first time reporting an issue so forgive me if I mislabel something. I just downloaded Pocket Sync for my Mac and connected it to my Pocket via USB. Every side tab on the app works, except the Games and Cores tab. As soon as I click on either, I get an Error message that reads

Games: null
Attempt to read platform_id pdp1
@tauri://localhost/assets/selectors-B936pI06.js:1:882

Cores: null
Attempt to read platform_id pdp1
@tauri://localhost/assets/selectors-B936pI06.js:1:882

ERROR AFTER THEN CLICKING POCKET SYNC TAB
Pocket Sync: null
Attempt to read platform_id pdp1
@tauri://localhost/assets/selectors-B936pI06.js:1:882

After these errors come up, then every other tab has an error until clicking "Retry"
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Pocket Sync screen 
2. Click on Game and Core Tab
3. See error(s)

**Expected behaviour**
I figured it would open up the Cores and Games sections to download. It ended up crashing the app, until I clicked "Retry" on another tab that wasn't Cores or Games

**Screenshots**
<img width="881" alt="Error When clicking Games Tab" src="https://github.com/user-attachments/assets/a6c72721-4162-4736-956b-b3bd2785f889">
<img width="878" alt="Error when clicking Cores Tab" src="https://github.com/user-attachments/assets/562d8bca-90db-4b52-a8d2-17ac8b6e2961">
<img width="873" alt="Subsequent Error aftert clicking Pocket Sync Tab" src="https://github.com/user-attachments/assets/819f2314-cb0a-4e7f-9672-2a9e97f8f9f3">
<img width="880" alt="Corrected Pocket Sync tab after clicking Retry" src="https://github.com/user-attachments/assets/c5dc4abc-3f89-4966-a93f-0b63e34f3b5f">

**Logs**
No logs come up after clicking on either tab and subsequently clicking Retry. Logs resume after clicking Retry on another tab.

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version [Sonoma 14.6.1]

**Additional context**
Thank you for your time, and all your work on Pocket Sync

**Comment by neil-morrison44** [comment]
Think this is the same issue as https://github.com/neil-morrison44/pocket-sync/issues/317

For some reason you're missing a file which should be at `Platforms/pdp1.json` - if you download that file from here https://github.com/spacemen3/PDP-1/tree/main/dist/Platforms and put it there it should resolve the issue

**Comment by Mr-GOJIRA-san** [comment]
Oh I see. It is strange, because it looks like the file is already there under Platforms. Am I missing a setp?
<img width="910" alt="File under Platform" src="https://github.com/user-attachments/assets/d26f35a0-abea-44ae-8a12-b68c898f5a31">

**Comment by Mr-GOJIRA-san** [comment]
I should say that I might've put another file in the wrong place, because I can only access Spacewar under the Builds setting in Pocket. Thank you so much for your help

**Comment by neil-morrison44** [comment]
What's in the json file? Could be the content is wrong & that'd explain why the Pocket itself is doing that too

**Comment by Mr-GOJIRA-san** [comment]
<img width="989" alt="Json File" src="https://github.com/user-attachments/assets/df44e2d8-23c3-4d5a-9f6c-f04ce6439f09">

**Comment by neil-morrison44** [comment]
That looks right, not sure what'd be going on.
Manually removing all pdp1 files & reinstalling should fix it

**Comment by Mr-GOJIRA-san** [comment]
Do you mean removing those files and reinstalling the Spacewar game?

**Comment by neil-morrison44** [comment]
Yeah, that should fix whatever difficulty both the Pocket & Pocket Sync are having with it - would be more confident if something looked wrong though

**Comment by Mr-GOJIRA-san** [comment]
Understood. I'll do it, and will let you know. Thank you so much

**Comment by Mr-GOJIRA-san** [comment]
It fixed it. Thank you again. Just curious, what are the differences between the snes cores? One says it supports Analogizer

**Comment by neil-morrison44** [comment]
That's the only difference yeah, means one works with this thing: https://analogizer-fpga.com/en/products/analogizer-fpga-adapter to get an Analog signal out without having to wait for official DAC support from Analogue themselves.

The Analogizer cores are (generally) modified from the main version & maintained by the Analogizer guy himself

**Comment by Mr-GOJIRA-san** [comment]
Goootchu. If I'm not using analogizer, then would it be best to uninstall it from my cores?

**Comment by neil-morrison44** [comment]
Yeah, no reason to have it if you've not got an Analogizer

**Comment by Mr-GOJIRA-san** [comment]
Awesome. Thank you so much Neil. I really appreciate your help, and work that you do.
