### ISSUE TITLE
Download All does nothing anymore.

### ISSUE THREAD

**Issue by xxsmbr** [neil-morrison44/pocket-sync#332]
It does not download anything.

Click the button - nothing happens.  Latest update.

**Comment by pinballgithub** [comment]
I can confirm - same in my Windows version.

**Comment by neil-morrison44** [comment]
https://archive.org/ is down just now.

Recommend temporarily following the instructions at https://www.reddit.com/r/AnaloguePocket/s/85CFhfknTv
