### ISSUE TITLE
Changed in JTBIN folders

### ISSUE THREAD

**Issue by jotego** [neil-morrison44/pocket-sync#34]
Hi, just to tell you that I moved the Pocket files in [JTBIN](https://github.com/jotego/jtbin) from /pocket to /pocket/raw, in order to have release zip files in /pocket/zip. 

Thank you for making life easier to users.

**Comment by neil-morrison44** [comment]
I noticed that thanks - would it be possible to zip up each core individually in JTBIN? 

That was the main thing we were thinking of creating the mirror repo for & if they’re individually packaged in jtbin it means the inventory can use the same code planned to support the pram0d cores: https://github.com/psomashekar/pram0d-pocket-dist-public/tree/develop/releases

Can see where we were discussing it here: https://github.com/joshcampbell191/openfpga-cores-inventory/issues/26

**Comment by jotego** [comment]
The GitHub action that creates the zip file is a very simple bash [script](https://github.com/jotego/jtbin/blob/master/.github/pocket_zip.sh). If you want to submit a specific script to be run in JTBIN as a GitHub action to make your work easier, you are welcome.

I don't want to have a collection of date-stamped zip files, like that in Pram0d's repository. There's already one for MiSTer and I'm thinking of getting rid of it. JTBIN is a git repository so you can simply use git to get an older version of the same file. I don't want to end up with more folders like this [one](https://github.com/jotego/jtbin/tree/master/mister/1942/releases) with lots of date-stamped files that make no sense after a while.

**Comment by neil-morrison44** [comment]
👍🏻 can do aye - Matt (of the CLI script) put together a workflow which does it & puts in a version number, but I'll have a go at making it more GitHub workflow native (&, potentially, run it through the validator) & raise a PR.

Having just the latest in the repo is probably fine (and makes more sense, the inventory'll need to deal with the dates for the parm0d cores)

The other thing with the cores is the version number - the updaters check the latest version number vs what's installed locally to know wether to update or not - currently it's set to `noversion` in the core.json so matt's script was using the githash of the most recently updated file - is this alright or would you prefer something else? (or, if you'd rather do it manually in the core.json that'd work too) - can be anything for the updaters so long as each release is different, it's probably what people'll refer to if they're reporting issues so whatever's good for that.

**Comment by jotego** [comment]
Thank you

I use _noversion_ in the JSON file because the file that holds the version is the **rbf** itself, which is what the FPGA loads. That version is the git commit code in my cores. It is visible when you enter the _core settings_ menu. The **rbf** gets recompiled often, whereas the JSON files tend not to change much.

I think the easiest way to detect a change in a core is simply asking git to tell you. See how we detect changes in MRA files in a GitHub action [here](https://github.com/jotego/jtbin/blob/master/.github/mra_sync.sh).
