### ISSUE TITLE
Feature request: Add an option to use custom GitHub tokens

### ISSUE THREAD

**Issue by ClassicOldSong** [neil-morrison44/pocket-sync#343]
**Is your feature request related to a problem? Please describe.**

Sometimes GitHub decides the API requests made by Pocket Sync is rate limited, suddenly the whole app isn't useable any more, even those local features that don't require GitHub API accesses. I have to wait half an hour for the limit to be lifted before I can do anything else.

**Describe the solution you'd like**

Provide an option to use a custom GitHub token that can have much higher API rate limit.

**Describe alternatives you've considered**

Download updates manually, but that defeats the purpose for using Pocket Sync.

**Comment by neil-morrison44** [comment]
What’s the usage pattern that uses up all the GitHub requests?

I’ve been reducing the requests where I can (the platforms info / artwork bit used to be 15 requests & now it’s 2) & I’ve not managed to hit the rate limit when “Updating All” a few dozen cores

**Comment by ClassicOldSong** [comment]
The limit isn't caused by Pocket Sync itself. I'm facing this issue quite often probably because of I'm using a VPN, as in China, I have to use a VPN to visit GitHub smoothly.

Luckily other tools I use can specify GitHub API tokens so their usage can be resumed, but Pocket Sync just shows a full page error and it stays there even after I switched to another tab. It'll be nice if either or all of them can be implemented:

1. Allow specifying a GitHub token 
2. Hide error after switching to a different tab

**Comment by neil-morrison44** [comment]
Ah right, if you click the “retry” button it (should) try to clear the error screen - so doing it after changing tab will show you whatever’s on that new tab (unless it errors too).

I’ll have a think about the GitHub token bit

**Comment by neil-morrison44** [comment]
That's a section for adding a github token added to settings as of v5.3.0 - I think it's everything but let me know if there's still anything that runs into rate limits

**Comment by ClassicOldSong** [comment]
Thanks! Much appreciate your attention!
