### ISSUE TITLE
Game Gear core shows old release as update

### ISSUE THREAD

**Issue by neogeo81** [neil-morrison44/pocket-sync#35]
On the Game Gear core it alway shows me the 1.2.0 as an update marked green although there is no 1.2.0 version and the actual latest one is 1.3.0 which is already installed.

**Comment by neil-morrison44** [comment]
Yeah that’s this https://github.com/spiritualized1997/openFPGA-GG/issues/6

though - the most recent versions of Pocket Sync should (incorrectly) show v1.2.0 as the latest which sort of fixes it, unless the inventory’s put in a workaround

**Comment by neogeo81** [comment]
No, not fixed with the latest update. Still shows 1.2.0 as an update

**Comment by neil-morrison44** [comment]
Oh I know what that’ll be - matt’s script has a hack in it that bumps the version to 1.3.0, so if the core came from there it’ll be set to 1.3.0 artificially
