### ISSUE TITLE
Still won’t work with OSX High Sierra 

### ISSUE THREAD

**Issue by Mika73** [neil-morrison44/pocket-sync#36]
I did try again. White screen, then it flash Pocket Sync start screen and black screen. Maybe one day it work with older MacOS too. Hope the best.

**Comment by neil-morrison44** [comment]
It’s unlikely, sorry - there’s no way for me to test on older macOS installations & with it failing so quickly I think it’s something I’m relying on that’s failing vs anything code I’ve written does.

There’s a trade off that the underlying tech I’m using (http://tauri.app) makes where it uses the system’s inbuilt browser which makes the apps small but it also makes them quite sensitive to what OS they’re running on in terms of what features are available etc

**Comment by neil-morrison44** [comment]
In built as in OS level - it’ll be whatever safari version there is (which, annoyingly, can’t be updated)
