### ISSUE TITLE
Error during tag_name parsing

### ISSUE THREAD

**Issue by tsalvo** [neil-morrison44/pocket-sync#39]
I think I was about to download one of the opengateware arcade cores, and perhaps this repo didn't have a release or tag (not 100% sure).  But I think the error is cached and stuck that way, because if I relaunch the Pocket Sync v1.7.0 app, and connect to the same SD card, I can't switch between tabs or navigate away from the error afterwards.  I'll try uninstalling / reinstalling, or connecting to a new SD card.

```
undefined is not an object (evaluating 't[0].tag_name')
@tauri://localhost/assets/index-7e9f8851.js:3163:58974
useMemo@tauri://localhost/assets/index-7e9f8851.js:6:25905
jte@tauri://localhost/assets/index-7e9f8851.js:3163:58965
OM@tauri://localhost/assets/index-7e9f8851.js:6:19559
aD@tauri://localhost/assets/index-7e9f8851.js:8:44430
iD@tauri://localhost/assets/index-7e9f8851.js:8:40067
g6@tauri://localhost/assets/index-7e9f8851.js:8:39995
Iy@tauri://localhost/assets/index-7e9f8851.js:8:39848
F1@tauri://localhost/assets/index-7e9f8851.js:8:36180
tD@tauri://localhost/assets/index-7e9f8851.js:8:35126
tD@[native code]
E@tauri://localhost/assets/index-7e9f8851.js:1:10047
re@tauri://localhost/assets/index-7e9f8851.js:1:10411
```

**Comment by neil-morrison44** [comment]
That's a weird one - the only place it does any `[0].tag_name` thing is when the app is checking its _own_ version on github.

If you leave the app closed for a while (long enough for github to reset any rate limiting things) does it start working again?

**Comment by tsalvo** [comment]
Yeah it works after waiting a few mins!  :-) Probably user error or something, I may have been causing too many GitHub API calls or something.  Sorry about that

**Comment by neil-morrison44** [comment]
no worries - it's something the app should handle better when it does happen

**Comment by neil-morrison44** [comment]
Closing this one with the improved error message
