### ISSUE TITLE
Question: can you rename core labels?

### ISSUE THREAD

**Issue by remy** [neil-morrison44/pocket-sync#4]
I've not been able to test yet, but this looks great. 

I wanted to know if renaming a core (or specifically it's label) such as "genesis" to "mega drive" is supported and whether it'll stick if there's a core update?

I guess the same question to categories too, as I tend to rename Jotego's cores to "arcade" rather than what they have as "arcade compatible".

Cheers.

**Comment by neil-morrison44** [comment]
Not yet - someone else asked for the ability to edit the platform images too, so I think I'll put in a page where all of that is viewable & editable (and, maybe, exportable)

If you've renamed manually you just need to uncheck the `Platforms/[platform name].json` file in any update / install and it'll not write over what you've got

**Comment by remy** [comment]
I actually suspect category rename support might be a better thing to prioritise over core labels now I think of it.

If I find myself with some spare time I'll see if I can do a PR to add support for this, though I've only got skills for the front-end side of bits. (If that's useful at all).

**Comment by neil-morrison44** [comment]
It’ll probably need a little bit of work on the rust side too to update the JSON files nicely + the platform images binaries, think it’ll be the next thing I look at, assuming no one discovers any massive bugs

**Comment by neil-morrison44** [comment]
<img width="303" alt="Screenshot 2022-11-27 at 17 48 06" src="https://user-images.githubusercontent.com/2095051/204151460-4eaa2877-2a7d-4acd-ab17-a04802b628e9.png">

There's a new section now (in v1.2.0) which allows you to change all the platform data
