### ISSUE TITLE
Unable to use the app

### ISSUE THREAD

**Issue by Wabbajackw** [neil-morrison44/pocket-sync#44]
The app doesn't work anymore, here displayed error:

GitHub rate limit reached, retry after 26/12/2022 18:39:24
Error: GitHub rate limit reached, retry after 26/12/2022 18:39:24
    at https://tauri.localhost/assets/index-1d29357c.js:10:74054

**Comment by neil-morrison44** [comment]
You've hit the github rate limit - you'll have to retry after 26/12/2022 18:39:24
