### ISSUE TITLE
The start window appears and immediately disappears

### ISSUE THREAD

**Issue by kostasmanana** [neil-morrison44/pocket-sync#45]
I found a bug on my Macbook Air Mid 2012 13", macOS Mojave 10.14.6. Tested versions 1.0.0 — 2.0.0.
I installed the application, but on the first launch, the start window appears and immediately disappears, leaving behind an empty gray application window, with which nothing can be done. Restarting, reinstalling, rebooting, with the connected Pocket and without, lead to the same effect. Please fix it.

https://user-images.githubusercontent.com/121864560/210345723-2f901196-7d88-421e-8c0b-f7bc6e73dba7.mov

**Comment by neil-morrison44** [comment]
Due to the framework I’m using to build the app (which uses the inbuilt safari browser) the only OSs I can reliably target are the latest one & one behind, sorry
