### ISSUE TITLE
Stuck Loading Core Data - macOS (Pokemon Mini, Pong, Slap Fight)

### ISSUE THREAD

**Issue by stevefish** [neil-morrison44/pocket-sync#46]
On my machine, the Pokemon Mini, Pong, and, Slap Fight cores get stuck when loading Cores details. These cores display well on the Platforms and Games pages, but the Cores details can't load when you click into them from there or when you visit the Cores page. Pokemon Mini and Pong were loaded manually, Slap Fight was loaded by Pocket Sync. I tried deleting all the related files for the Slap Fight core and allowing Pocket Sync to reinstall them, but received the same results. I've not had similar problems with any of the other cores - some of which were successfully set up by Pocket Sync. 

Here are my system specs:
- Analogue Pocket - 1st Generation
- macOS - Ventura 13.0.1 (22A400)
- Pocket Sync - Version 2.0.0 (20221224.040553)

Thank you for looking into this. If you need me to test anything else or provide additional information, just let me know.

**Comment by gregmariotti** [comment]
same issue here. it's just spinning for the slapfight core...

**Comment by neil-morrison44** [comment]
The slapfight issue's simple enough (it's the first core not to have an associated author icon) - the Pokemon Mini & Pong ones are a bit strange.

@stevefish do you mind zipping up the files in `Cores/agg23.Pong` and sending them over? can hopefully see what's gone wrong that way.

**Comment by stevefish** [comment]
> @stevefish do you mind zipping up the files in your `Cores/agg23.Pong` and sending them over? can hopefully see what's gone wrong that way.

Sure thing. Here they are!
[agg23.Pong.zip](https://github.com/neil-morrison44/pocket-sync/files/10341262/agg23.Pong.zip)

**Comment by neil-morrison44** [comment]
Oh that's interesting - it's also not got the `icon.bin` file (the Pong I have has it though, so I'm not sure how that happened)

The same fix that went in for the slapfight core in v2.0.1 should fix those

**Comment by stevefish** [comment]
In a fit of experimentation, I manually deleted Pong from the Cores and Platform folders my SD Card, updated to PS 2.0.1 and used it to install Pong, and now none of the cores (including Pokemon Mini, which I didn't delete) have the problem reported above. I think this proves that PS 2.0.1 should fix this problem and I'm grateful!
