### ISSUE TITLE
GitHub rate limit reached

### ISSUE THREAD

**Issue by MrBoydee** [neil-morrison44/pocket-sync#50]
GitHub rate limit reached, retry after 07/01/2023, 23:11:14
@tauri://localhost/assets/index-8f6733b8.js:10:74063
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]

**Comment by neil-morrison44** [comment]
Yeah, that happens - just need to wait until the time in the error message. Usually only happens when one of the other updaters has been run within the hour.

there’ll be an update to the inventory to prevent it soon
