### ISSUE TITLE
JSON Parse error

### ISSUE THREAD

**Issue by mrpablington** [neil-morrison44/pocket-sync#59]
JSON Parse error: Unexpected comma at the end of array expression
parse@[native code]
@tauri://localhost/assets/index-9f9c9e3f.js:16:255012
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]

**Comment by P-C-R** [comment]
same here
SON Parse error: Unexpected comma at the end of array expression
parse@[native code]
@tauri://localhost/assets/index-9f9c9e3f.js:16:2910
@[native code]

**Comment by neogeo81** [comment]
Same here:

JSON Parse error: Unexpected comma at the end of array expression
parse@[native code]
@tauri://localhost/assets/index-9f9c9e3f.js:16:255012
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]

**Comment by neil-morrison44** [comment]
That's this issue: https://github.com/Mazamars312/Analogue_Pocket_Neogeo/pull/43 I believe

Out of interest though - how long does the neogeo's page take to open for you?

**Comment by neogeo81** [comment]
Very long. I had to update it manually. After that when I want to look at
it it crashes.

Neil Morrison ***@***.***> schrieb am Sa., 14. Jan. 2023,
15:10:

**Comment by neil-morrison44** [comment]
Should be fixed now in v2.2.1
