### ISSUE TITLE
GUI briefly appears and then disappears - OSX

### ISSUE THREAD

**Issue by MutantClaw** [neil-morrison44/pocket-sync#62]
Upon opening this app the GUI briefly appears and then disappears, leaving a blank screen. Running it on OSX 10.14.6
App Version 2.2.1 (20230114.164936)
<img width="992" alt="Screen Shot 2023-01-16 at 12 14 05 PM" src="https://user-images.githubusercontent.com/106338748/212734508-3ccf51f0-a88a-43fe-a244-4034efe4a597.png">

**Comment by neil-morrison44** [comment]
Hey, sorry - I'm not able to support MacOS versions older than the last major 2 (if it _did_ load then there'd be a bunch of broken stuff in the UI) 

I've added a FAQ section about this now https://github.com/neil-morrison44/pocket-sync#why-doesnt-this-work-on-older-macos-version
