### ISSUE TITLE
Connection to Pocket Fails on MacOS

### ISSUE THREAD

**Issue by cmcginty** [neil-morrison44/pocket-sync#63]
Mac OS Monterey 12.5

Apologies, but the setup is not entirely clear. I have a pocket with correctly formatted SD card. When I click "connect to pocket" there is a slight delay but the pocket device is not visible in the file browser that opens. 

Are there examples of how the connection process should behave on MacOS?

**Comment by neil-morrison44** [comment]
Can you see the Pocket in the regular Finder app?

It should just be a case of selecting the root of the SD card as a folder in that browser

**Comment by cmcginty** [comment]
I figured it out. There is an option in "Tools -> Developer -> USB SD Access" that has to be turned on first, before it will connect. Also the instructions should specify that the the goal is to navigate to the root of the mounted pocket SD card. I can submit a PR if you would like.

**Comment by neil-morrison44** [comment]
The root folder step is already mentioned in the readme here: https://github.com/neil-morrison44/pocket-sync#installation
