### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by terminator2k2** [neil-morrison44/pocket-sync#67]
Just got this error message trying to view a platform image on windows

Expected double-quoted property name in JSON at position 674
SyntaxError: Expected double-quoted property name in JSON at position 674
    at JSON.parse (<anonymous>)
    at https://tauri.localhost/assets/index-4c12b94e.js:16:3496

**Comment by neil-morrison44** [comment]
Which core / platform were you looking at when this came up?

**Comment by terminator2k2** [comment]
Does it on all of them since a added a alpha test core
