### ISSUE TITLE
Installing cores via zip file not checking for folders in correct heirarchy

### ISSUE THREAD

**Issue by mfncl9991** [neil-morrison44/pocket-sync#68]
First, many thanks for providing this wonderful tool. I wanted to suggest an enhancement to the core installation routine when installing a new core from a zip file (for example JT beta cores).

When dragging a zip file into the UI, the UI helpfully shows the contents and lets you pick what you want to extract to the SD card.

However, it does not appear to check the zip files folder layout to ensure it places the folders in the correct heirarchy on the destination SD card.
It makes the assumption that the ZIP file contains the Platforms, Assets, Cores and Presets folders are located at the root.

In some cases this may not be the case, see below example the JT beta core update zips - where the contents that need extracting the to pocket SD card are situated in the `pocket` subfolder:

![image](https://user-images.githubusercontent.com/51936111/214875285-3b45455c-5008-4239-80fb-ed81bbb5918b.png)

When installing this zip via Pocket Sync, it leads to an invalid folder structure.
As a workaround, I have to recompress the contents of `pocket` into a separate archive.

It seems Pocket Sync is already checking ZIP file contents for things to exclude (like .MACOSX foider) - suggest adding a subroutine to make sure the folders are copied to the right location.

**Comment by neil-morrison44** [comment]
Thanks for the nice words!

So in Pocket Sync I don't want to be responsible for repairing any bad input (like the zips).

I've made another tool that core devs can use to validate their cores: https://github.com/neil-morrison44/openfpga-validator but I don't think it's got widespread usage yet. Hopefully that changes & I get feedback on how to make it more helpful.

While Pocket Sync _could_ search through the zip trying to find the right folder it'd open up a bunch more challenges like:
- what if it's an art asset pack and only has the `Platforms` folder
- What if there's a folder that looks good but the files in it are wrong, or if there's a nested folder
- What if there's multiple cores defined in the same zip in a non-standard way
- plus more, I've seen .rar files too

I don't particularly feel like solving all these in Pocket Sync

What it could do is display a warning if the zip doesn't look like a core zip (i.e. it fails validation) - but I'm not sure how helpful this would be Vs it just listing all the files as it does now

**Comment by mfncl9991** [comment]
Thanks Neil, this makes sense. Let's hope the standardized approach to packaging cores etgs adopted in the future :)
