### ISSUE TITLE
Catalina (10.15) Support

### ISSUE THREAD

**Issue by curiositycasualty** [neil-morrison44/pocket-sync#70]
The app launches to blank grey screen on Mac OS 10.15(.7) aka Catalina. Connected, disconnecting, reconnecting via USB seems to have no effect. Yes, "USB SD Access" is enabled, `pocket-updated-utility` works for example.

Granted, this is my miraculously not-yet-dead `MacBook Pro (Retina, 13-inch, Late 2012)`...

**Comment by neil-morrison44** [comment]
Annoyingly, I can only really support the last 2 major versions of MacOS (since Apple doesn’t keep WebKit up to date on older OSes) - bit more info here: https://github.com/neil-morrison44/pocket-sync#why-doesnt-this-work-on-older-macos-version
