### ISSUE TITLE
MacOS 11: Error / crash on clicking "image packs"

### ISSUE THREAD

**Issue by remy** [neil-morrison44/pocket-sync#74]
**Describe the bug**

Manually added the jtcps1 core and related files to my SD card. Then loaded Pocket Sync, selected "Platforms", then "jtcps1" then clicked on "Image Packs" (I didn't know what it would do) and it crashes with:

```
Platforms: jtcps1
options.signal must be AbortSignal
pipeThrough@[native code]
gS@tauri://localhost/assets/index-09e71954.js:3200:1104040
tauri://localhost/assets/index-09e71954.js:3200:1107497
asyncFunctionResume@[native code]
tauri://localhost/assets/index-09e71954.js:3201:1161148
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
```

Retry lets me repeat the process.

If I don't click retry, the sidebar links don't work - it just keeps the error and changes `Platforms: jtcps1` to `Games: null`, etc.

**Screenshots**

![](https://remysharp.com/shot/SCR-20230203-ik3-min.png)

**Desktop (please complete the following information):**
 - OS: macOS big sur
 - Pocket Sync Version: 2.4.0

**Comment by neil-morrison44** [comment]
I think the image packs on the jtcps1 core worked for me so I'm not sure what this would be - can you zip up your `Platforms` folder & attach it here, can see if there's anything weird going on there?

**Comment by neil-morrison44** [comment]
Congrats on finding an error where the only two google results are when it was implemented in webkit though: https://www.google.com/search?q=%22options.signal+must+be+AbortSignal%22

**Comment by misterrichterrrr** [comment]
Came here to report the same bug. Didn't click a specific platform though. Was trying to see if you can download different image packs within the software. 

Platforms: null
options.signal must be AbortSignal
pipeThrough@[native code]
gS@tauri://localhost/assets/index-5fe25fcd.js:3200:1104170
tauri://localhost/assets/index-5fe25fcd.js:3200:1107547
asyncFunctionResume@[native code]
tauri://localhost/assets/index-5fe25fcd.js:3201:1161278
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]

**Comment by remy** [comment]
Sorry, meant to do this, but got distracted (SQUIRREL!) - attached:

[Platforms.zip](https://github.com/neil-morrison44/pocket-sync/files/10684926/Platforms.zip)

**Comment by misterrichterrrr** [comment]
I'm using Version 2.5.0 (20230206.222615)

I hope this helps!

[Platforms.zip](https://github.com/neil-morrison44/pocket-sync/files/10689134/Platforms.zip)

**Comment by neil-morrison44** [comment]
Thanks for those, hopefully they'll help - what version of MacOS are you both on?

**Comment by misterrichterrrr** [comment]
Mac OS 11.5.2

Also realized in the root of my SD card I have Matt Panella's pocket_updater. 
Not sure if that causes any sort of issue.

**Comment by remy** [comment]
I'm on Big Sur, 11.7.

**Comment by neil-morrison44** [comment]
Interesting - hopefully it's not something Apple fixed after 11 since I'll need to find a way to go back to 11...

@misterrichterrrr switching between the updaters should all be fine

**Comment by neil-morrison44** [comment]
There _might be_ a fix for this in v2.6.0 - there used to be one request done via a normal `fetch` & one request done by a tauri `http` thing (for CORS reasons) and now I've made them both the tauri `http` thing.

It's a little bit more likely it'll mean that _both_ break but at least I'll have narrowed down what's going wrong a little & can try and report it to tauri.

**Comment by Arithmeticae** [comment]
Just chiming in to say I'm experiencing the same issue. I'm on MacOS 11.7.3. using version 2.6.1 of the updater.

<img width="1306" alt="Screen Shot 2023-02-20 at 2 48 33 PM" src="https://user-images.githubusercontent.com/15927569/220188232-bb3bf7d9-17ac-4350-a37e-b66721a5bebc.png">

[Platforms.zip](https://github.com/neil-morrison44/pocket-sync/files/10787438/Platforms.zip)

**Comment by neil-morrison44** [comment]
Well that narrows it down at least, thanks

I've reported this upstream, but I suspect the issue's with the actual version of Webkit included in MacOS 11 & unless there's a workaround the only solution is probably to upgrade to 12+
