### ISSUE TITLE
Blank Screen in MacOS Ventura 13.1 beta

### ISSUE THREAD

**Issue by digitalmud** [neil-morrison44/pocket-sync#8]
When I launch the app on an M2 MacBook, running MacOS Ventura 13.1 all that launches is a blank / white screen.

**Comment by neil-morrison44** [comment]
Are you using the 13.1 beta? I'm on 13.0.1 (the latest non-beta) and it works

**Comment by digitalmud** [comment]
Yes - definitely the beta.

**Comment by neil-morrison44** [comment]
Closing this off since it works fine for me in the full release of 13.1
