### ISSUE TITLE
Platforms -> Image Packs List Missaligned - Mac OS 11

### ISSUE THREAD

**Issue by Arithmeticae** [neil-morrison44/pocket-sync#83]
When viewing the list of Image Packs, the Rows in the **Current** column do not align with the rows in the adjacent columns. It appears like the images in the other columns are 2x the desired height.

<img width="1730" alt="Screen Shot 2023-02-27 at 1 18 08 PM" src="https://user-images.githubusercontent.com/15927569/221649976-80ad57c2-2ea4-4e4c-8d78-ef07b4dc38cb.png">

I observe this issue on MacOS 11.7.4.

**Comment by neil-morrison44** [comment]
Closing the MacOS 11 issues since it's now 5 versions older than the most recent & I just can't support that far back due to the way Tauri uses the system Webkit.
