### ISSUE TITLE
Add cheat codes for the cores.

### ISSUE THREAD

**Issue by ThetaX55** [neil-morrison44/pocket-sync#89]
The cores seam not to have cheat codes. Please get them to add them. 
Good thing save stats are in.

**Comment by neil-morrison44** [comment]
I'm not sure who you think I am, I'm not Analogue.
Adding cheat codes is far outside the realm of possibility for this app, or any updater.

I suggest you either:
- Read the [Analogue Pocket Docs](https://www.analogue.co/developer/docs/getting-started), come up with a standard way of doing cheat codes that'd work in every core (if that's even possible) then raise PRs on every core with the feature added.
- Email Analogue customer support (once) requesting the feature and wait
