### ISSUE TITLE
MiSTer Save Sync - pocket-sync looks for PC Engine CD saves in the wrong location?

### ISSUE THREAD

**Issue by fluiddruid** [neil-morrison44/pocket-sync#96]
On my MiSTer, the PC Engine CD game saves are located in /media/fat/saves/TGFX16 (even though the games themselves are under /media/fat/games/TGFX16-CD - I think the problem is that the MiSTer core doesn't discriminate between CD and non-CD games when writing saves, so puts everything in the TGFX16 directory).

pocket-sync is only checking /media/fat/saves/TGFX16-CD on the MiSTer and so can't sync my PC Engine CD saves.

All other systems (including non-CD PC Engine games) get their saves synced fine.

I'm running pocket-sync v3.0.0 on a Windows 11 PC, and my MiSTer is up to date - MiSTer software v230223, Turbo Duo Core v23.02.24.

**Comment by fluiddruid** [comment]
Should have mentioned that I'm running pocket-sync v3.0.0 on a Windows 11 PC, and my MiSTer is up to date.

**Comment by neil-morrison44** [comment]
Ah yeah, I was wondering about that & assumed everything would follow the game folder's name. Should be a quick enough fix, thanks for letting me know everything else works

**Comment by fluiddruid** [comment]
Thank you for jumping on this so quickly! I was away last week so couldn't test it immediately, but I've just taken a look and can confirm that it's fixed in V3.0.1.
